/* Generated by MyraPad at 09.06.2019 15:31:53 */
using Myra.Graphics2D.UI;

namespace TroublesOfJord.MapEditor.UI
{
	public partial class NewMapDialog: Dialog
	{
		public NewMapDialog()
		{
			BuildUI();
		}
	}
}