/* Generated by MyraPad at 17.10.2019 22:34:04 */
using Myra.Graphics2D.UI;

#if !XENKO
using Microsoft.Xna.Framework;
#else
using Xenko.Core.Mathematics;
#endif

namespace Wanderers.UI
{
	partial class CharacterImage: Grid
	{
		private void BuildUI()
		{
			_textName = new Label();
			_textName.Text = "Henry";
			_textName.Wrap = true;
			_textName.Id = "_textName";

			var label1 = new Label();
			label1.Text = "HP:";
			label1.Wrap = true;

			var label2 = new Label();
			label2.Text = "IP:";
			label2.Wrap = true;
			label2.Id = "";
			label2.GridRow = 1;

			_textHP = new Label();
			_textHP.Text = "100/100";
			_textHP.Wrap = true;
			_textHP.Id = "_textHP";
			_textHP.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Center;
			_textHP.GridColumn = 1;

			_textIP = new Label();
			_textIP.Text = "100/100";
			_textIP.Wrap = true;
			_textIP.Id = "_textIP";
			_textIP.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Center;
			_textIP.GridColumn = 1;
			_textIP.GridRow = 1;

			var grid1 = new Grid();
			grid1.RowSpacing = 4;
			grid1.DefaultRowProportion = new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Auto,
			};
			grid1.ColumnsProportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Auto,
			});
			grid1.ColumnsProportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Fill,
			});
			grid1.GridRow = 2;
			grid1.Widgets.Add(label1);
			grid1.Widgets.Add(label2);
			grid1.Widgets.Add(_textHP);
			grid1.Widgets.Add(_textIP);

			
			ShowGridLines = true;
			RowSpacing = 4;
			RowsProportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Auto,
			});
			RowsProportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Fill,
				Value = 6,
			});
			RowsProportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Auto,
			});
			HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Left;
			VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Top;
			Id = "Root";
			Width = 200;
			Height = 300;
			Widgets.Add(_textName);
			Widgets.Add(grid1);
		}

		
		public Label _textName;
		public Label _textHP;
		public Label _textIP;
	}
}