/* Generated by Myra UI Editor at 23.02.2019 20:46:06 */
using Microsoft.Xna.Framework;
using Myra.Graphics2D.UI;

namespace Wanderers.UI
{
	partial class CharacterImage
	{
		private void BuildUI()
		{
			_textName = new TextBlock();
			_textName.Text = "Henry";
			_textName.Wrap = true;
			_textName.Id = "_textName";

			var textBlock1 = new TextBlock();
			textBlock1.Text = "HP:";
			textBlock1.Wrap = true;

			var textBlock2 = new TextBlock();
			textBlock2.Text = "IP:";
			textBlock2.Wrap = true;
			textBlock2.Id = "";
			textBlock2.GridRow = 1;

			_textHP = new TextBlock();
			_textHP.Text = "100/100";
			_textHP.Wrap = true;
			_textHP.Id = "_textHP";
			_textHP.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Center;
			_textHP.GridColumn = 1;

			_textIP = new TextBlock();
			_textIP.Text = "100/100";
			_textIP.Wrap = true;
			_textIP.Id = "_textIP";
			_textIP.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Center;
			_textIP.GridColumn = 1;
			_textIP.GridRow = 1;

			var grid1 = new Grid();
			grid1.RowSpacing = 4;
			grid1.ColumnsProportions.Add(new Grid.Proportion());
			grid1.ColumnsProportions.Add(new Grid.Proportion
			{
				Type = Myra.Graphics2D.UI.Grid.ProportionType.Fill,
			});
			grid1.RowsProportions.Add(new Grid.Proportion());
			grid1.RowsProportions.Add(new Grid.Proportion());
			grid1.GridRow = 2;
			grid1.Widgets.Add(textBlock1);
			grid1.Widgets.Add(textBlock2);
			grid1.Widgets.Add(_textHP);
			grid1.Widgets.Add(_textIP);

			
			ShowGridLines = true;
			RowSpacing = 4;
			RowsProportions.Add(new Grid.Proportion());
			RowsProportions.Add(new Grid.Proportion
			{
				Type = Myra.Graphics2D.UI.Grid.ProportionType.Fill,
				Value = 6,
			});
			RowsProportions.Add(new Grid.Proportion());
			HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Left;
			VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Top;
			Id = "Root";
			Width = 200;
			Height = 300;
			Widgets.Add(_textName);
			Widgets.Add(grid1);
		}

		
		public TextBlock _textName;
		public TextBlock _textHP;
		public TextBlock _textIP;
	}
}