/* Generated by MyraPad at 17.10.2019 22:28:27 */
using Myra.Graphics2D.UI;

#if !XENKO
using Microsoft.Xna.Framework;
#else
using Xenko.Core.Mathematics;
#endif

namespace Wanderers.UI
{
	partial class CharacterGenerationDialog: Dialog
	{
		private void BuildUI()
		{
			var label1 = new Label();
			label1.Text = "Name:";

			_textName = new TextBox();
			_textName.Text = "";
			_textName.Id = "_textName";
			_textName.GridColumn = 1;

			var label2 = new Label();
			label2.Text = "Class:";
			label2.GridRow = 2;

			var listItem1 = new ListItem();
			listItem1.Id = null;
			listItem1.Text = "Warrior";

			var listItem2 = new ListItem();
			listItem2.Id = null;
			listItem2.Text = "Rogue";

			var listItem3 = new ListItem();
			listItem3.Id = null;
			listItem3.Text = "Priest";

			var listItem4 = new ListItem();
			listItem4.Id = null;
			listItem4.Text = "Mage";

			_comboClass = new ComboBox();
			_comboClass.Id = "_comboClass";
			_comboClass.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Stretch;
			_comboClass.GridColumn = 1;
			_comboClass.GridRow = 2;
			_comboClass.Items.Add(listItem1);
			_comboClass.Items.Add(listItem2);
			_comboClass.Items.Add(listItem3);
			_comboClass.Items.Add(listItem4);

			var grid1 = new Grid();
			grid1.ColumnSpacing = 8;
			grid1.RowSpacing = 4;
			grid1.DefaultRowProportion = new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Auto,
			};
			grid1.ColumnsProportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Auto,
			});
			grid1.ColumnsProportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Fill,
			});
			grid1.Widgets.Add(label1);
			grid1.Widgets.Add(_textName);
			grid1.Widgets.Add(label2);
			grid1.Widgets.Add(_comboClass);

			
			Title = "Create Character";
			Left = 424;
			Top = 187;
			Width = 200;
			Content = grid1;
		}

		
		public TextBox _textName;
		public ComboBox _comboClass;
	}
}