/* Generated by MyraPad at 15.03.2019 0:55:15 */
using Microsoft.Xna.Framework;
using Myra.Graphics2D.UI;

namespace Wanderers.UI
{
	partial class CharacterGenerationDialog
	{
		private void BuildUI()
		{
			var textBlock1 = new TextBlock();
			textBlock1.Text = "Name:";

			_textName = new TextField();
			_textName.Text = "";
			_textName.Id = "_textName";
			_textName.GridColumn = 1;

			var textBlock2 = new TextBlock();
			textBlock2.Text = "Class:";
			textBlock2.GridRow = 2;

			var listItem1 = new ListItem();
			listItem1.Id = null;
			listItem1.Text = "Warrior";

			var listItem2 = new ListItem();
			listItem2.Id = null;
			listItem2.Text = "Rogue";

			var listItem3 = new ListItem();
			listItem3.Id = null;
			listItem3.Text = "Priest";

			var listItem4 = new ListItem();
			listItem4.Id = null;
			listItem4.Text = "Mage";

			_comboClass = new ComboBox();
			_comboClass.Id = "_comboClass";
			_comboClass.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Stretch;
			_comboClass.GridColumn = 1;
			_comboClass.GridRow = 2;
			_comboClass.Items.Add(listItem1);
			_comboClass.Items.Add(listItem2);
			_comboClass.Items.Add(listItem3);
			_comboClass.Items.Add(listItem4);

			var grid1 = new Grid();
			grid1.ColumnSpacing = 8;
			grid1.RowSpacing = 4;
			grid1.ColumnsProportions.Add(new Grid.Proportion());
			grid1.ColumnsProportions.Add(new Grid.Proportion
			{
				Type = Myra.Graphics2D.UI.Grid.ProportionType.Fill,
			});
			grid1.RowsProportions.Add(new Grid.Proportion());
			grid1.RowsProportions.Add(new Grid.Proportion());
			grid1.GridRow = 1;
			grid1.Widgets.Add(textBlock1);
			grid1.Widgets.Add(_textName);
			grid1.Widgets.Add(textBlock2);
			grid1.Widgets.Add(_comboClass);

			
			Title = "Create Character";
			Left = 373;
			Top = 128;
			Width = 200;
			Content = grid1;
		}

		
		public TextField _textName;
		public ComboBox _comboClass;
	}
}