/* Generated by MyraPad at 28.10.2019 22:48:56 */
using Myra.Graphics2D.UI;

#if !XENKO
using Microsoft.Xna.Framework;
#else
using Xenko.Core.Mathematics;
#endif

namespace Wanderers.UI
{
	partial class GameView: HorizontalStackPanel
	{
		private void BuildUI()
		{
			_mapViewContainer = new Panel();
			_mapViewContainer.Id = "_mapViewContainer";

			var verticalSeparator1 = new VerticalSeparator();

			_labelHp = new Label();
			_labelHp.Text = "H: 50/100";
			_labelHp.Id = "_labelHp";
			_labelHp.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Center;

			var verticalSeparator2 = new VerticalSeparator();

			_labelMana = new Label();
			_labelMana.Text = "M: 50/100";
			_labelMana.Id = "_labelMana";
			_labelMana.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Center;

			var verticalSeparator3 = new VerticalSeparator();

			_labelEnergy = new Label();
			_labelEnergy.Text = "E: 50/100";
			_labelEnergy.Id = "_labelEnergy";
			_labelEnergy.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Center;

			var horizontalStackPanel1 = new HorizontalStackPanel();
			horizontalStackPanel1.Proportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Part,
			});
			horizontalStackPanel1.Proportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Auto,
			});
			horizontalStackPanel1.Proportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Part,
			});
			horizontalStackPanel1.Proportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Auto,
			});
			horizontalStackPanel1.Proportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Part,
			});
			horizontalStackPanel1.Widgets.Add(_labelHp);
			horizontalStackPanel1.Widgets.Add(verticalSeparator2);
			horizontalStackPanel1.Widgets.Add(_labelMana);
			horizontalStackPanel1.Widgets.Add(verticalSeparator3);
			horizontalStackPanel1.Widgets.Add(_labelEnergy);

			var horizontalSeparator1 = new HorizontalSeparator();

			_mapContainer = new Panel();
			_mapContainer.Id = "_mapContainer";
			_mapContainer.Height = 247;

			var horizontalSeparator2 = new HorizontalSeparator();

			_logContainer = new Panel();
			_logContainer.Id = "_logContainer";

			var verticalStackPanel1 = new VerticalStackPanel();
			verticalStackPanel1.Widgets.Add(horizontalStackPanel1);
			verticalStackPanel1.Widgets.Add(horizontalSeparator1);
			verticalStackPanel1.Widgets.Add(_mapContainer);
			verticalStackPanel1.Widgets.Add(horizontalSeparator2);
			verticalStackPanel1.Widgets.Add(_logContainer);

			
			Proportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Part,
				Value = 2,
			});
			Proportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Auto,
			});
			Proportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Part,
			});
			Widgets.Add(_mapViewContainer);
			Widgets.Add(verticalSeparator1);
			Widgets.Add(verticalStackPanel1);
		}

		
		public Panel _mapViewContainer;
		public Label _labelHp;
		public Label _labelMana;
		public Label _labelEnergy;
		public Panel _mapContainer;
		public Panel _logContainer;
	}
}