/* Generated by MyraPad at 17.10.2019 22:30:57 */
using Myra.Graphics2D.UI;

#if !XENKO
using Microsoft.Xna.Framework;
#else
using Xenko.Core.Mathematics;
#endif

namespace Wanderers.UI
{
	partial class InventoryWindow: Window
	{
		private void BuildUI()
		{
			_textNameLeft = new Label();
			_textNameLeft.Text = "Equipment";
			_textNameLeft.Id = "_textNameLeft";

			var label1 = new Label();
			label1.Text = "<light>";

			var label2 = new Label();
			label2.Text = "eye of the deep";
			label2.GridColumn = 1;

			var label3 = new Label();
			label3.Text = "<left finger>";
			label3.GridRow = 1;

			var label4 = new Label();
			label4.Text = "a carved wooden ring";
			label4.GridColumn = 1;
			label4.GridRow = 1;

			var label5 = new Label();
			label5.Text = "<right finger>";
			label5.GridRow = 2;

			var label6 = new Label();
			label6.Text = "a carved wooden ring";
			label6.GridColumn = 1;
			label6.GridRow = 2;

			var label7 = new Label();
			label7.Text = "<neck 1>";
			label7.GridRow = 3;

			var label8 = new Label();
			label8.Text = "the amulet of the sanguineous magi";
			label8.GridColumn = 1;
			label8.GridRow = 3;

			var label9 = new Label();
			label9.Text = "<neck 2>";
			label9.GridRow = 4;

			var label10 = new Label();
			label10.Text = "the amulet of the sanguineous magi";
			label10.GridColumn = 1;
			label10.GridRow = 4;

			var label11 = new Label();
			label11.Text = "<body>";
			label11.GridRow = 5;

			var label12 = new Label();
			label12.Text = "a gilded corset of crimson and gold";
			label12.GridColumn = 1;
			label12.GridRow = 5;

			var label13 = new Label();
			label13.Text = "<head>";
			label13.GridRow = 6;

			var label14 = new Label();
			label14.Text = "The Crown of Thorns";
			label14.GridColumn = 1;
			label14.GridRow = 6;

			var label15 = new Label();
			label15.Text = "<legs>";
			label15.GridRow = 7;

			var label16 = new Label();
			label16.Text = "Ogre Hide Leggings";
			label16.GridColumn = 1;
			label16.GridRow = 7;

			var label17 = new Label();
			label17.Text = "<feet>";
			label17.GridRow = 8;

			var label18 = new Label();
			label18.Text = "a pair of dolphin skin boots";
			label18.GridColumn = 1;
			label18.GridRow = 8;

			var label19 = new Label();
			label19.Text = "<hands>";
			label19.GridRow = 9;

			var label20 = new Label();
			label20.Text = "gloves of the yellow rose";
			label20.GridColumn = 1;
			label20.GridRow = 9;

			var label21 = new Label();
			label21.Text = "<arms>";
			label21.GridRow = 10;

			var label22 = new Label();
			label22.Text = "a set of tidal sleeves";
			label22.GridColumn = 1;
			label22.GridRow = 10;

			var label23 = new Label();
			label23.Text = "<shield>";
			label23.GridRow = 11;

			var label24 = new Label();
			label24.Text = "an intricately decorated shield";
			label24.GridColumn = 1;
			label24.GridRow = 11;

			var label25 = new Label();
			label25.Text = "<about body>";
			label25.GridRow = 12;

			var label26 = new Label();
			label26.Text = "a dragonwing tunic";
			label26.GridColumn = 1;
			label26.GridRow = 12;

			var label27 = new Label();
			label27.Text = "<waist>";
			label27.GridRow = 13;

			var label28 = new Label();
			label28.Text = "a golden belt";
			label28.GridColumn = 1;
			label28.GridRow = 13;

			var label29 = new Label();
			label29.Text = "<left wrist>";
			label29.GridRow = 14;

			var label30 = new Label();
			label30.Text = "tanzanite bracelet";
			label30.GridColumn = 1;
			label30.GridRow = 14;

			var label31 = new Label();
			label31.Text = "<right wrist>";
			label31.GridRow = 15;

			var label32 = new Label();
			label32.Text = "tanzanite bracelet";
			label32.GridColumn = 1;
			label32.GridRow = 15;

			var label33 = new Label();
			label33.Text = "<wielded>";
			label33.GridRow = 16;

			var label34 = new Label();
			label34.Text = "a secari dagger";
			label34.GridColumn = 1;
			label34.GridRow = 16;

			var label35 = new Label();
			label35.Text = "<held>";
			label35.GridRow = 17;

			var label36 = new Label();
			label36.Text = "a moss-covered pebble";
			label36.GridColumn = 1;
			label36.GridRow = 17;

			_gridEquipment = new Grid();
			_gridEquipment.ColumnSpacing = 8;
			_gridEquipment.RowSpacing = 4;
			_gridEquipment.DefaultColumnProportion = new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Auto,
			};
			_gridEquipment.DefaultRowProportion = new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Auto,
			};
			_gridEquipment.GridSelectionMode = Myra.Graphics2D.UI.GridSelectionMode.Row;
			_gridEquipment.Id = "_gridEquipment";
			_gridEquipment.GridRow = 1;
			_gridEquipment.Widgets.Add(label1);
			_gridEquipment.Widgets.Add(label2);
			_gridEquipment.Widgets.Add(label3);
			_gridEquipment.Widgets.Add(label4);
			_gridEquipment.Widgets.Add(label5);
			_gridEquipment.Widgets.Add(label6);
			_gridEquipment.Widgets.Add(label7);
			_gridEquipment.Widgets.Add(label8);
			_gridEquipment.Widgets.Add(label9);
			_gridEquipment.Widgets.Add(label10);
			_gridEquipment.Widgets.Add(label11);
			_gridEquipment.Widgets.Add(label12);
			_gridEquipment.Widgets.Add(label13);
			_gridEquipment.Widgets.Add(label14);
			_gridEquipment.Widgets.Add(label15);
			_gridEquipment.Widgets.Add(label16);
			_gridEquipment.Widgets.Add(label17);
			_gridEquipment.Widgets.Add(label18);
			_gridEquipment.Widgets.Add(label19);
			_gridEquipment.Widgets.Add(label20);
			_gridEquipment.Widgets.Add(label21);
			_gridEquipment.Widgets.Add(label22);
			_gridEquipment.Widgets.Add(label23);
			_gridEquipment.Widgets.Add(label24);
			_gridEquipment.Widgets.Add(label25);
			_gridEquipment.Widgets.Add(label26);
			_gridEquipment.Widgets.Add(label27);
			_gridEquipment.Widgets.Add(label28);
			_gridEquipment.Widgets.Add(label29);
			_gridEquipment.Widgets.Add(label30);
			_gridEquipment.Widgets.Add(label31);
			_gridEquipment.Widgets.Add(label32);
			_gridEquipment.Widgets.Add(label33);
			_gridEquipment.Widgets.Add(label34);
			_gridEquipment.Widgets.Add(label35);
			_gridEquipment.Widgets.Add(label36);

			var grid1 = new Grid();
			grid1.ShowGridLines = true;
			grid1.ColumnSpacing = 8;
			grid1.RowSpacing = 8;
			grid1.DefaultRowProportion = new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Auto,
			};
			grid1.Widgets.Add(_textNameLeft);
			grid1.Widgets.Add(_gridEquipment);

			_textNameRight = new Label();
			_textNameRight.Text = "Inventory";
			_textNameRight.Id = "_textNameRight";

			_textGoldRight = new Label();
			_textGoldRight.Text = "Gold: 50000";
			_textGoldRight.Id = "_textGoldRight";
			_textGoldRight.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Right;

			var panel1 = new Panel();
			panel1.Widgets.Add(_textNameRight);
			panel1.Widgets.Add(_textGoldRight);

			var label37 = new Label();
			label37.Text = "iron rations(100)";

			var label38 = new Label();
			label38.Text = "canteen";
			label38.GridRow = 1;

			var label39 = new Label();
			label39.Text = "barrel";
			label39.GridRow = 2;

			var label40 = new Label();
			label40.Text = "short sword";
			label40.GridRow = 3;

			var label41 = new Label();
			label41.Text = "leather armor";
			label41.GridRow = 4;

			var label42 = new Label();
			label42.Text = "leather leggings";
			label42.GridRow = 5;

			var label43 = new Label();
			label43.Text = "small shield";
			label43.GridRow = 6;

			_gridInventory = new Grid();
			_gridInventory.ColumnSpacing = 8;
			_gridInventory.RowSpacing = 4;
			_gridInventory.DefaultRowProportion = new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Auto,
			};
			_gridInventory.ColumnsProportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Fill,
			});
			_gridInventory.GridSelectionMode = Myra.Graphics2D.UI.GridSelectionMode.Row;
			_gridInventory.Id = "_gridInventory";
			_gridInventory.Widgets.Add(label37);
			_gridInventory.Widgets.Add(label38);
			_gridInventory.Widgets.Add(label39);
			_gridInventory.Widgets.Add(label40);
			_gridInventory.Widgets.Add(label41);
			_gridInventory.Widgets.Add(label42);
			_gridInventory.Widgets.Add(label43);

			var scrollViewer1 = new ScrollViewer();
			scrollViewer1.GridRow = 1;
			scrollViewer1.Content = _gridInventory;

			var grid2 = new Grid();
			grid2.ShowGridLines = true;
			grid2.ColumnSpacing = 8;
			grid2.RowSpacing = 8;
			grid2.DefaultRowProportion = new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Auto,
			};
			grid2.GridColumn = 1;
			grid2.Widgets.Add(panel1);
			grid2.Widgets.Add(scrollViewer1);

			var grid3 = new Grid();
			grid3.ShowGridLines = true;
			grid3.ColumnSpacing = 8;
			grid3.Widgets.Add(grid1);
			grid3.Widgets.Add(grid2);

			_textDescription = new Label();
			_textDescription.Text = "short sword - weapon, damage: 3-8";
			_textDescription.Id = "_textDescription";
			_textDescription.GridRow = 1;

			var grid4 = new Grid();
			grid4.ShowGridLines = true;
			grid4.RowsProportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Fill,
			});
			grid4.RowsProportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Auto,
			});
			grid4.Width = 1000;
			grid4.Height = 520;
			grid4.PaddingTop = 16;
			grid4.PaddingBottom = 16;
			grid4.Widgets.Add(grid3);
			grid4.Widgets.Add(_textDescription);

			
			Title = "Items";
			Left = 24;
			Content = grid4;
		}

		
		public Label _textNameLeft;
		public Grid _gridEquipment;
		public Label _textNameRight;
		public Label _textGoldRight;
		public Grid _gridInventory;
		public Label _textDescription;
	}
}