/* Generated by MyraPad at 17.03.2019 18:15:24 */
using Microsoft.Xna.Framework;
using Myra.Graphics2D.UI;

namespace Wanderers.UI
{
	partial class InventoryWindow
	{
		private void BuildUI()
		{
			_textNameLeft = new TextBlock();
			_textNameLeft.Text = "Equipment";
			_textNameLeft.Id = "_textNameLeft";

			var textBlock1 = new TextBlock();
			textBlock1.Text = "<light>";

			var textBlock2 = new TextBlock();
			textBlock2.Text = "eye of the deep";
			textBlock2.GridColumn = 1;

			var textBlock3 = new TextBlock();
			textBlock3.Text = "<left finger>";
			textBlock3.GridRow = 1;

			var textBlock4 = new TextBlock();
			textBlock4.Text = "a carved wooden ring";
			textBlock4.GridColumn = 1;
			textBlock4.GridRow = 1;

			var textBlock5 = new TextBlock();
			textBlock5.Text = "<right finger>";
			textBlock5.GridRow = 2;

			var textBlock6 = new TextBlock();
			textBlock6.Text = "a carved wooden ring";
			textBlock6.GridColumn = 1;
			textBlock6.GridRow = 2;

			var textBlock7 = new TextBlock();
			textBlock7.Text = "<neck 1>";
			textBlock7.GridRow = 3;

			var textBlock8 = new TextBlock();
			textBlock8.Text = "the amulet of the sanguineous magi";
			textBlock8.GridColumn = 1;
			textBlock8.GridRow = 3;

			var textBlock9 = new TextBlock();
			textBlock9.Text = "<neck 2>";
			textBlock9.GridRow = 4;

			var textBlock10 = new TextBlock();
			textBlock10.Text = "the amulet of the sanguineous magi";
			textBlock10.GridColumn = 1;
			textBlock10.GridRow = 4;

			var textBlock11 = new TextBlock();
			textBlock11.Text = "<body>";
			textBlock11.GridRow = 5;

			var textBlock12 = new TextBlock();
			textBlock12.Text = "a gilded corset of crimson and gold";
			textBlock12.GridColumn = 1;
			textBlock12.GridRow = 5;

			var textBlock13 = new TextBlock();
			textBlock13.Text = "<head>";
			textBlock13.GridRow = 6;

			var textBlock14 = new TextBlock();
			textBlock14.Text = "The Crown of Thorns";
			textBlock14.GridColumn = 1;
			textBlock14.GridRow = 6;

			var textBlock15 = new TextBlock();
			textBlock15.Text = "<legs>";
			textBlock15.GridRow = 7;

			var textBlock16 = new TextBlock();
			textBlock16.Text = "Ogre Hide Leggings";
			textBlock16.GridColumn = 1;
			textBlock16.GridRow = 7;

			var textBlock17 = new TextBlock();
			textBlock17.Text = "<feet>";
			textBlock17.GridRow = 8;

			var textBlock18 = new TextBlock();
			textBlock18.Text = "a pair of dolphin skin boots";
			textBlock18.GridColumn = 1;
			textBlock18.GridRow = 8;

			var textBlock19 = new TextBlock();
			textBlock19.Text = "<hands>";
			textBlock19.GridRow = 9;

			var textBlock20 = new TextBlock();
			textBlock20.Text = "gloves of the yellow rose";
			textBlock20.GridColumn = 1;
			textBlock20.GridRow = 9;

			var textBlock21 = new TextBlock();
			textBlock21.Text = "<arms>";
			textBlock21.GridRow = 10;

			var textBlock22 = new TextBlock();
			textBlock22.Text = "a set of tidal sleeves";
			textBlock22.GridColumn = 1;
			textBlock22.GridRow = 10;

			var textBlock23 = new TextBlock();
			textBlock23.Text = "<shield>";
			textBlock23.GridRow = 11;

			var textBlock24 = new TextBlock();
			textBlock24.Text = "an intricately decorated shield";
			textBlock24.GridColumn = 1;
			textBlock24.GridRow = 11;

			var textBlock25 = new TextBlock();
			textBlock25.Text = "<about body>";
			textBlock25.GridRow = 12;

			var textBlock26 = new TextBlock();
			textBlock26.Text = "a dragonwing tunic";
			textBlock26.GridColumn = 1;
			textBlock26.GridRow = 12;

			var textBlock27 = new TextBlock();
			textBlock27.Text = "<waist>";
			textBlock27.GridRow = 13;

			var textBlock28 = new TextBlock();
			textBlock28.Text = "a golden belt";
			textBlock28.GridColumn = 1;
			textBlock28.GridRow = 13;

			var textBlock29 = new TextBlock();
			textBlock29.Text = "<left wrist>";
			textBlock29.GridRow = 14;

			var textBlock30 = new TextBlock();
			textBlock30.Text = "tanzanite bracelet";
			textBlock30.GridColumn = 1;
			textBlock30.GridRow = 14;

			var textBlock31 = new TextBlock();
			textBlock31.Text = "<right wrist>";
			textBlock31.GridRow = 15;

			var textBlock32 = new TextBlock();
			textBlock32.Text = "tanzanite bracelet";
			textBlock32.GridColumn = 1;
			textBlock32.GridRow = 15;

			var textBlock33 = new TextBlock();
			textBlock33.Text = "<wielded>";
			textBlock33.GridRow = 16;

			var textBlock34 = new TextBlock();
			textBlock34.Text = "a secari dagger";
			textBlock34.GridColumn = 1;
			textBlock34.GridRow = 16;

			var textBlock35 = new TextBlock();
			textBlock35.Text = "<held>";
			textBlock35.GridRow = 17;

			var textBlock36 = new TextBlock();
			textBlock36.Text = "a moss-covered pebble";
			textBlock36.GridColumn = 1;
			textBlock36.GridRow = 17;

			_gridEquipment = new Grid();
			_gridEquipment.ColumnSpacing = 8;
			_gridEquipment.RowSpacing = 4;
			_gridEquipment.ColumnsProportions.Add(new Grid.Proportion());
			_gridEquipment.ColumnsProportions.Add(new Grid.Proportion());
			_gridEquipment.RowsProportions.Add(new Grid.Proportion());
			_gridEquipment.RowsProportions.Add(new Grid.Proportion());
			_gridEquipment.RowsProportions.Add(new Grid.Proportion());
			_gridEquipment.RowsProportions.Add(new Grid.Proportion());
			_gridEquipment.RowsProportions.Add(new Grid.Proportion());
			_gridEquipment.RowsProportions.Add(new Grid.Proportion());
			_gridEquipment.RowsProportions.Add(new Grid.Proportion());
			_gridEquipment.RowsProportions.Add(new Grid.Proportion());
			_gridEquipment.RowsProportions.Add(new Grid.Proportion());
			_gridEquipment.RowsProportions.Add(new Grid.Proportion());
			_gridEquipment.RowsProportions.Add(new Grid.Proportion());
			_gridEquipment.RowsProportions.Add(new Grid.Proportion());
			_gridEquipment.RowsProportions.Add(new Grid.Proportion());
			_gridEquipment.RowsProportions.Add(new Grid.Proportion());
			_gridEquipment.RowsProportions.Add(new Grid.Proportion());
			_gridEquipment.RowsProportions.Add(new Grid.Proportion());
			_gridEquipment.RowsProportions.Add(new Grid.Proportion());
			_gridEquipment.RowsProportions.Add(new Grid.Proportion());
			_gridEquipment.GridSelectionMode = Myra.Graphics2D.UI.GridSelectionMode.Row;
			_gridEquipment.Id = "_gridEquipment";
			_gridEquipment.GridRow = 1;
			_gridEquipment.Widgets.Add(textBlock1);
			_gridEquipment.Widgets.Add(textBlock2);
			_gridEquipment.Widgets.Add(textBlock3);
			_gridEquipment.Widgets.Add(textBlock4);
			_gridEquipment.Widgets.Add(textBlock5);
			_gridEquipment.Widgets.Add(textBlock6);
			_gridEquipment.Widgets.Add(textBlock7);
			_gridEquipment.Widgets.Add(textBlock8);
			_gridEquipment.Widgets.Add(textBlock9);
			_gridEquipment.Widgets.Add(textBlock10);
			_gridEquipment.Widgets.Add(textBlock11);
			_gridEquipment.Widgets.Add(textBlock12);
			_gridEquipment.Widgets.Add(textBlock13);
			_gridEquipment.Widgets.Add(textBlock14);
			_gridEquipment.Widgets.Add(textBlock15);
			_gridEquipment.Widgets.Add(textBlock16);
			_gridEquipment.Widgets.Add(textBlock17);
			_gridEquipment.Widgets.Add(textBlock18);
			_gridEquipment.Widgets.Add(textBlock19);
			_gridEquipment.Widgets.Add(textBlock20);
			_gridEquipment.Widgets.Add(textBlock21);
			_gridEquipment.Widgets.Add(textBlock22);
			_gridEquipment.Widgets.Add(textBlock23);
			_gridEquipment.Widgets.Add(textBlock24);
			_gridEquipment.Widgets.Add(textBlock25);
			_gridEquipment.Widgets.Add(textBlock26);
			_gridEquipment.Widgets.Add(textBlock27);
			_gridEquipment.Widgets.Add(textBlock28);
			_gridEquipment.Widgets.Add(textBlock29);
			_gridEquipment.Widgets.Add(textBlock30);
			_gridEquipment.Widgets.Add(textBlock31);
			_gridEquipment.Widgets.Add(textBlock32);
			_gridEquipment.Widgets.Add(textBlock33);
			_gridEquipment.Widgets.Add(textBlock34);
			_gridEquipment.Widgets.Add(textBlock35);
			_gridEquipment.Widgets.Add(textBlock36);

			var grid1 = new Grid();
			grid1.ShowGridLines = true;
			grid1.ColumnSpacing = 8;
			grid1.RowSpacing = 8;
			grid1.RowsProportions.Add(new Grid.Proportion());
			grid1.RowsProportions.Add(new Grid.Proportion());
			grid1.Widgets.Add(_textNameLeft);
			grid1.Widgets.Add(_gridEquipment);

			_textNameRight = new TextBlock();
			_textNameRight.Text = "Inventory";
			_textNameRight.Id = "_textNameRight";

			_textGoldRight = new TextBlock();
			_textGoldRight.Text = "Gold: 50000";
			_textGoldRight.Id = "_textGoldRight";
			_textGoldRight.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Right;

			var panel1 = new Panel();
			panel1.Widgets.Add(_textNameRight);
			panel1.Widgets.Add(_textGoldRight);

			var textBlock37 = new TextBlock();
			textBlock37.Text = "iron rations(100)";

			var textBlock38 = new TextBlock();
			textBlock38.Text = "canteen";
			textBlock38.GridRow = 1;

			var textBlock39 = new TextBlock();
			textBlock39.Text = "barrel";
			textBlock39.GridRow = 2;

			var textBlock40 = new TextBlock();
			textBlock40.Text = "short sword";
			textBlock40.GridRow = 3;

			var textBlock41 = new TextBlock();
			textBlock41.Text = "leather armor";
			textBlock41.GridRow = 4;

			var textBlock42 = new TextBlock();
			textBlock42.Text = "leather leggings";
			textBlock42.GridRow = 5;

			var textBlock43 = new TextBlock();
			textBlock43.Text = "small shield";
			textBlock43.GridRow = 6;

			_gridInventory = new Grid();
			_gridInventory.ColumnSpacing = 8;
			_gridInventory.RowSpacing = 4;
			_gridInventory.ColumnsProportions.Add(new Grid.Proportion
			{
				Type = Myra.Graphics2D.UI.Grid.ProportionType.Fill,
			});
			_gridInventory.RowsProportions.Add(new Grid.Proportion());
			_gridInventory.RowsProportions.Add(new Grid.Proportion());
			_gridInventory.RowsProportions.Add(new Grid.Proportion());
			_gridInventory.RowsProportions.Add(new Grid.Proportion());
			_gridInventory.RowsProportions.Add(new Grid.Proportion());
			_gridInventory.RowsProportions.Add(new Grid.Proportion());
			_gridInventory.RowsProportions.Add(new Grid.Proportion());
			_gridInventory.RowsProportions.Add(new Grid.Proportion());
			_gridInventory.GridSelectionMode = Myra.Graphics2D.UI.GridSelectionMode.Row;
			_gridInventory.Id = "_gridInventory";
			_gridInventory.Widgets.Add(textBlock37);
			_gridInventory.Widgets.Add(textBlock38);
			_gridInventory.Widgets.Add(textBlock39);
			_gridInventory.Widgets.Add(textBlock40);
			_gridInventory.Widgets.Add(textBlock41);
			_gridInventory.Widgets.Add(textBlock42);
			_gridInventory.Widgets.Add(textBlock43);

			var scrollPane1 = new ScrollPane();
			scrollPane1.GridRow = 1;
			scrollPane1.Child = _gridInventory;

			var grid2 = new Grid();
			grid2.ShowGridLines = true;
			grid2.ColumnSpacing = 8;
			grid2.RowSpacing = 8;
			grid2.RowsProportions.Add(new Grid.Proportion());
			grid2.RowsProportions.Add(new Grid.Proportion());
			grid2.GridColumn = 1;
			grid2.Widgets.Add(panel1);
			grid2.Widgets.Add(scrollPane1);

			var grid3 = new Grid();
			grid3.ShowGridLines = true;
			grid3.ColumnSpacing = 8;
			grid3.ColumnsProportions.Add(new Grid.Proportion
			{
				Type = Myra.Graphics2D.UI.Grid.ProportionType.Part,
			});
			grid3.ColumnsProportions.Add(new Grid.Proportion
			{
				Type = Myra.Graphics2D.UI.Grid.ProportionType.Part,
			});
			grid3.Widgets.Add(grid1);
			grid3.Widgets.Add(grid2);

			_textDescription = new TextBlock();
			_textDescription.Text = "short sword - weapon, damage: 3-8";
			_textDescription.Id = "_textDescription";
			_textDescription.GridRow = 1;

			var grid4 = new Grid();
			grid4.ShowGridLines = true;
			grid4.RowsProportions.Add(new Grid.Proportion
			{
				Type = Myra.Graphics2D.UI.Grid.ProportionType.Fill,
			});
			grid4.RowsProportions.Add(new Grid.Proportion());
			grid4.Width = 1000;
			grid4.Height = 520;
			grid4.PaddingTop = 16;
			grid4.PaddingBottom = 16;
			grid4.GridRow = 1;
			grid4.Widgets.Add(grid3);
			grid4.Widgets.Add(_textDescription);

			
			Title = "Items";
			Left = 213;
			Top = 68;
			Content = grid4;
		}

		
		public TextBlock _textNameLeft;
		public Grid _gridEquipment;
		public TextBlock _textNameRight;
		public TextBlock _textGoldRight;
		public Grid _gridInventory;
		public TextBlock _textDescription;
	}
}