/* Generated by MyraPad at 08.03.2019 2:16:22 */
using Microsoft.Xna.Framework;
using Myra.Graphics2D.UI;

namespace Wanderers.UI
{
	partial class MainMenu
	{
		private void BuildUI()
		{
			var textBlock1 = new TextBlock();
			textBlock1.Text = "Troubles of Jord";
			textBlock1.TextColor = new Color
			{
				B = 64,
				G = 128,
				R = 255,
				A = 255,
			};
			textBlock1.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Center;

			_startNewGameMenuItem = new MenuItem();
			_startNewGameMenuItem.Id = "_startNewGameMenuItem";
			_startNewGameMenuItem.Text = "Start New Game";

			_optionsMenuItem = new MenuItem();
			_optionsMenuItem.Id = "_optionsMenuItem";
			_optionsMenuItem.Text = "Options";

			_quitMenuItem = new MenuItem();
			_quitMenuItem.Id = "_quitMenuItem";
			_quitMenuItem.Text = "Quit";

			_mainMenu = new VerticalMenu();
			_mainMenu.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Center;
			_mainMenu.VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Center;
			_mainMenu.Id = "_mainMenu";
			_mainMenu.Items.Add(_startNewGameMenuItem);
			_mainMenu.Items.Add(_optionsMenuItem);
			_mainMenu.Items.Add(_quitMenuItem);

			_textVersion = new TextBlock();
			_textVersion.Text = "Version 1.0";
			_textVersion.TextColor = Color.Lime;
			_textVersion.Id = "_textVersion";
			_textVersion.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Right;
			_textVersion.VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Bottom;

			
			Id = "Root";
			Widgets.Add(textBlock1);
			Widgets.Add(_mainMenu);
			Widgets.Add(_textVersion);
		}

		
		public MenuItem _startNewGameMenuItem;
		public MenuItem _optionsMenuItem;
		public MenuItem _quitMenuItem;
		public VerticalMenu _mainMenu;
		public TextBlock _textVersion;
	}
}