/* Generated by MyraPad at 16.03.2019 22:02:57 */
using Microsoft.Xna.Framework;
using Myra.Graphics2D.UI;

namespace Wanderers.UI
{
	partial class TradeDialog
	{
		private void BuildUI()
		{
			_textNameLeft = new TextBlock();
			_textNameLeft.Text = "player";
			_textNameLeft.Id = "_textNameLeft";

			_textGoldLeft = new TextBlock();
			_textGoldLeft.Text = "Gold: 1000";
			_textGoldLeft.Id = "_textGoldLeft";
			_textGoldLeft.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Right;

			var panel1 = new Panel();
			panel1.Widgets.Add(_textNameLeft);
			panel1.Widgets.Add(_textGoldLeft);

			var textBlock1 = new TextBlock();
			textBlock1.Text = "iron rations(5)";
			textBlock1.GridColumn = 1;

			var textBlock2 = new TextBlock();
			textBlock2.Text = "5";
			textBlock2.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Right;
			textBlock2.GridColumn = 2;

			var textBlock3 = new TextBlock();
			textBlock3.Text = "canteen";
			textBlock3.GridColumn = 1;
			textBlock3.GridRow = 1;

			var textBlock4 = new TextBlock();
			textBlock4.Text = "7";
			textBlock4.GridColumn = 2;
			textBlock4.GridRow = 1;

			_gridLeft = new Grid();
			_gridLeft.ColumnSpacing = 8;
			_gridLeft.RowSpacing = 4;
			_gridLeft.ColumnsProportions.Add(new Grid.Proportion
			{
				Type = Myra.Graphics2D.UI.Grid.ProportionType.Pixels,
				Value = 16,
			});
			_gridLeft.ColumnsProportions.Add(new Grid.Proportion
			{
				Type = Myra.Graphics2D.UI.Grid.ProportionType.Fill,
			});
			_gridLeft.ColumnsProportions.Add(new Grid.Proportion());
			_gridLeft.RowsProportions.Add(new Grid.Proportion());
			_gridLeft.RowsProportions.Add(new Grid.Proportion());
			_gridLeft.GridSelectionMode = Myra.Graphics2D.UI.GridSelectionMode.Row;
			_gridLeft.Id = "_gridLeft";
			_gridLeft.Widgets.Add(textBlock1);
			_gridLeft.Widgets.Add(textBlock2);
			_gridLeft.Widgets.Add(textBlock3);
			_gridLeft.Widgets.Add(textBlock4);

			var scrollPane1 = new ScrollPane();
			scrollPane1.GridRow = 1;
			scrollPane1.Child = _gridLeft;

			var grid1 = new Grid();
			grid1.ShowGridLines = true;
			grid1.ColumnSpacing = 8;
			grid1.RowSpacing = 8;
			grid1.RowsProportions.Add(new Grid.Proportion());
			grid1.RowsProportions.Add(new Grid.Proportion());
			grid1.Widgets.Add(panel1);
			grid1.Widgets.Add(scrollPane1);

			_textGoldTransfer = new TextBlock();
			_textGoldTransfer.Text = "500";
			_textGoldTransfer.Id = "_textGoldTransfer";
			_textGoldTransfer.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Center;

			_panelArrow = new Panel();
			_panelArrow.Id = "_panelArrow";
			_panelArrow.Height = 20;
			_panelArrow.GridRow = 1;

			_gridGoldTransfer = new Grid();
			_gridGoldTransfer.RowsProportions.Add(new Grid.Proportion());
			_gridGoldTransfer.RowsProportions.Add(new Grid.Proportion());
			_gridGoldTransfer.VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Center;
			_gridGoldTransfer.Id = "_gridGoldTransfer";
			_gridGoldTransfer.GridColumn = 1;
			_gridGoldTransfer.Widgets.Add(_textGoldTransfer);
			_gridGoldTransfer.Widgets.Add(_panelArrow);

			_textNameRight = new TextBlock();
			_textNameRight.Text = "merchant";
			_textNameRight.Id = "_textNameRight";

			_textGoldRight = new TextBlock();
			_textGoldRight.Text = "Gold: 50000";
			_textGoldRight.Id = "_textGoldRight";
			_textGoldRight.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Right;

			var panel2 = new Panel();
			panel2.Widgets.Add(_textNameRight);
			panel2.Widgets.Add(_textGoldRight);

			var textBlock5 = new TextBlock();
			textBlock5.Text = "iron rations(100)";
			textBlock5.GridColumn = 1;

			var textBlock6 = new TextBlock();
			textBlock6.Text = "10";
			textBlock6.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Right;
			textBlock6.GridColumn = 2;

			var textBlock7 = new TextBlock();
			textBlock7.Text = "canteen";
			textBlock7.GridColumn = 1;
			textBlock7.GridRow = 1;

			var textBlock8 = new TextBlock();
			textBlock8.Text = "15";
			textBlock8.GridColumn = 2;
			textBlock8.GridRow = 1;

			var textBlock9 = new TextBlock();
			textBlock9.Text = "barrel";
			textBlock9.GridColumn = 1;
			textBlock9.GridRow = 2;

			var textBlock10 = new TextBlock();
			textBlock10.Text = "25";
			textBlock10.GridColumn = 2;
			textBlock10.GridRow = 2;

			var textBlock11 = new TextBlock();
			textBlock11.Text = "short sword";
			textBlock11.GridColumn = 1;
			textBlock11.GridRow = 3;

			var textBlock12 = new TextBlock();
			textBlock12.Text = "50";
			textBlock12.GridColumn = 2;
			textBlock12.GridRow = 3;

			var textBlock13 = new TextBlock();
			textBlock13.Text = "leather armor";
			textBlock13.GridColumn = 1;
			textBlock13.GridRow = 4;

			var textBlock14 = new TextBlock();
			textBlock14.Text = "40";
			textBlock14.GridColumn = 2;
			textBlock14.GridRow = 4;

			var textBlock15 = new TextBlock();
			textBlock15.Text = "leather leggings";
			textBlock15.GridColumn = 1;
			textBlock15.GridRow = 5;

			var textBlock16 = new TextBlock();
			textBlock16.Text = "30";
			textBlock16.GridColumn = 2;
			textBlock16.GridRow = 5;

			var textBlock17 = new TextBlock();
			textBlock17.Text = "small shield";
			textBlock17.GridColumn = 1;
			textBlock17.GridRow = 6;

			var textBlock18 = new TextBlock();
			textBlock18.Text = "25";
			textBlock18.GridColumn = 2;
			textBlock18.GridRow = 6;

			_gridRight = new Grid();
			_gridRight.ColumnSpacing = 8;
			_gridRight.RowSpacing = 4;
			_gridRight.ColumnsProportions.Add(new Grid.Proportion
			{
				Type = Myra.Graphics2D.UI.Grid.ProportionType.Pixels,
				Value = 16,
			});
			_gridRight.ColumnsProportions.Add(new Grid.Proportion
			{
				Type = Myra.Graphics2D.UI.Grid.ProportionType.Fill,
			});
			_gridRight.ColumnsProportions.Add(new Grid.Proportion());
			_gridRight.RowsProportions.Add(new Grid.Proportion());
			_gridRight.RowsProportions.Add(new Grid.Proportion());
			_gridRight.RowsProportions.Add(new Grid.Proportion());
			_gridRight.RowsProportions.Add(new Grid.Proportion());
			_gridRight.RowsProportions.Add(new Grid.Proportion());
			_gridRight.RowsProportions.Add(new Grid.Proportion());
			_gridRight.RowsProportions.Add(new Grid.Proportion());
			_gridRight.RowsProportions.Add(new Grid.Proportion());
			_gridRight.GridSelectionMode = Myra.Graphics2D.UI.GridSelectionMode.Row;
			_gridRight.Id = "_gridRight";
			_gridRight.Widgets.Add(textBlock5);
			_gridRight.Widgets.Add(textBlock6);
			_gridRight.Widgets.Add(textBlock7);
			_gridRight.Widgets.Add(textBlock8);
			_gridRight.Widgets.Add(textBlock9);
			_gridRight.Widgets.Add(textBlock10);
			_gridRight.Widgets.Add(textBlock11);
			_gridRight.Widgets.Add(textBlock12);
			_gridRight.Widgets.Add(textBlock13);
			_gridRight.Widgets.Add(textBlock14);
			_gridRight.Widgets.Add(textBlock15);
			_gridRight.Widgets.Add(textBlock16);
			_gridRight.Widgets.Add(textBlock17);
			_gridRight.Widgets.Add(textBlock18);

			var scrollPane2 = new ScrollPane();
			scrollPane2.GridRow = 1;
			scrollPane2.Child = _gridRight;

			var grid2 = new Grid();
			grid2.ShowGridLines = true;
			grid2.ColumnSpacing = 8;
			grid2.RowSpacing = 4;
			grid2.RowsProportions.Add(new Grid.Proportion());
			grid2.RowsProportions.Add(new Grid.Proportion());
			grid2.GridColumn = 2;
			grid2.Widgets.Add(panel2);
			grid2.Widgets.Add(scrollPane2);

			var grid3 = new Grid();
			grid3.ColumnSpacing = 8;
			grid3.ColumnsProportions.Add(new Grid.Proportion
			{
				Type = Myra.Graphics2D.UI.Grid.ProportionType.Part,
			});
			grid3.ColumnsProportions.Add(new Grid.Proportion
			{
				Type = Myra.Graphics2D.UI.Grid.ProportionType.Pixels,
				Value = 100,
			});
			grid3.ColumnsProportions.Add(new Grid.Proportion
			{
				Type = Myra.Graphics2D.UI.Grid.ProportionType.Part,
			});
			grid3.Widgets.Add(grid1);
			grid3.Widgets.Add(_gridGoldTransfer);
			grid3.Widgets.Add(grid2);

			_textDescription = new TextBlock();
			_textDescription.Text = "short sword - weapon, damage: 3-8";
			_textDescription.Id = "_textDescription";
			_textDescription.GridRow = 1;

			var grid4 = new Grid();
			grid4.ShowGridLines = true;
			grid4.RowsProportions.Add(new Grid.Proportion
			{
				Type = Myra.Graphics2D.UI.Grid.ProportionType.Fill,
			});
			grid4.RowsProportions.Add(new Grid.Proportion());
			grid4.Width = 800;
			grid4.Height = 400;
			grid4.PaddingTop = 16;
			grid4.PaddingBottom = 16;
			grid4.GridRow = 1;
			grid4.Widgets.Add(grid3);
			grid4.Widgets.Add(_textDescription);

			
			Title = "Trade";
			Left = 313;
			Top = 113;
			Content = grid4;
		}

		
		public TextBlock _textNameLeft;
		public TextBlock _textGoldLeft;
		public Grid _gridLeft;
		public TextBlock _textGoldTransfer;
		public Panel _panelArrow;
		public Grid _gridGoldTransfer;
		public TextBlock _textNameRight;
		public TextBlock _textGoldRight;
		public Grid _gridRight;
		public TextBlock _textDescription;
	}
}