/* Generated by MyraPad at 10/9/2022 5:34:35 AM */
using Myra;
using Myra.Graphics2D;
using Myra.Graphics2D.TextureAtlases;
using Myra.Graphics2D.UI;
using Myra.Graphics2D.Brushes;
using Myra.Graphics2D.UI.Properties;
using FontStashSharp.RichText;

namespace Jord.MapEditor.UI
{
	partial class GenerateWorldDialog: Dialog
	{
		private void BuildUI()
		{
			_properties = new PropertyGrid();
			_properties.Id = "_properties";

			_labelStatus = new Label();
			_labelStatus.Text = "Status String";
			_labelStatus.Id = "_labelStatus";

			var verticalStackPanel1 = new VerticalStackPanel();
			verticalStackPanel1.Spacing = 8;
			verticalStackPanel1.Widgets.Add(_properties);
			verticalStackPanel1.Widgets.Add(_labelStatus);

			
			Title = "Generate World...";
			Left = 280;
			Top = 285;
			Width = 500;
			Content = verticalStackPanel1;
		}

		
		public PropertyGrid _properties;
		public Label _labelStatus;
	}
}
