/* Generated by MyraPad at 11/10/2023 8:56:43 PM */
using Myra;
using Myra.Graphics2D;
using Myra.Graphics2D.TextureAtlases;
using Myra.Graphics2D.UI;
using Myra.Graphics2D.Brushes;
using Myra.Graphics2D.UI.Properties;
using FontStashSharp.RichText;
using AssetManagementBase;

#if STRIDE
using Stride.Core.Mathematics;
#elif PLATFORM_AGNOSTIC
using System.Drawing;
using System.Numerics;
using Color = FontStashSharp.FSColor;
#else
// MonoGame/FNA
using Microsoft.Xna.Framework;
using Microsoft.Xna.Framework.Graphics;
#endif

namespace Jord.MapEditor.UI
{
	partial class GenerateMapDialog: Dialog
	{
		private void BuildUI()
		{
			_comboGenerator = new ComboBox();
			_comboGenerator.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Stretch;
			_comboGenerator.VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Center;
			_comboGenerator.Id = "_comboGenerator";

			var label1 = new Label();
			label1.Text = "Generate...";

			_buttonGenerate = new Button();
			_buttonGenerate.VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Center;
			_buttonGenerate.Id = "_buttonGenerate";
			_buttonGenerate.Content = label1;

			var label2 = new Label();
			label2.Text = "Step:";
			label2.VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Center;

			_spinButtonStep = new SpinButton();
			_spinButtonStep.Minimum = 0;
			_spinButtonStep.Value = 6;
			_spinButtonStep.Integer = true;
			_spinButtonStep.Width = 50;
			_spinButtonStep.Id = "_spinButtonStep";

			var label3 = new Label();
			label3.Text = "Set to 0";

			_buttonZeroStep = new Button();
			_buttonZeroStep.VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Center;
			_buttonZeroStep.Id = "_buttonZeroStep";
			_buttonZeroStep.Content = label3;

			var horizontalStackPanel1 = new HorizontalStackPanel();
			horizontalStackPanel1.Spacing = 8;
			horizontalStackPanel1.Widgets.Add(_comboGenerator);
			horizontalStackPanel1.Widgets.Add(_buttonGenerate);
			horizontalStackPanel1.Widgets.Add(label2);
			horizontalStackPanel1.Widgets.Add(_spinButtonStep);
			horizontalStackPanel1.Widgets.Add(_buttonZeroStep);

			_panelResult = new Panel();
			_panelResult.Id = "_panelResult";
			StackPanel.SetProportionType(_panelResult, Myra.Graphics2D.UI.ProportionType.Fill);

			var verticalStackPanel1 = new VerticalStackPanel();
			verticalStackPanel1.Spacing = 8;
			verticalStackPanel1.Width = 800;
			verticalStackPanel1.Widgets.Add(horizontalStackPanel1);
			verticalStackPanel1.Widgets.Add(_panelResult);

			
			Title = "Generate Map";
			Left = 553;
			Top = 31;
			Height = 600;
			Content = verticalStackPanel1;
		}

		
		public ComboBox _comboGenerator;
		public Button _buttonGenerate;
		public SpinButton _spinButtonStep;
		public Button _buttonZeroStep;
		public Panel _panelResult;
	}
}
