/* Generated by MyraPad at 23.10.2019 22:51:30 */
using Myra.Graphics2D.UI;

#if !XENKO
using Microsoft.Xna.Framework;
#else
using Xenko.Core.Mathematics;
#endif

namespace Jord.MapEditor.UI
{
	partial class NewMapDialog: Dialog
	{
		private void BuildUI()
		{
			_radioSingleTileMap = new RadioButton();
			_radioSingleTileMap.Text = "Single Tile Map";
			_radioSingleTileMap.Id = "_radioSingleTileMap";

			_radioGeneratedMap = new RadioButton();
			_radioGeneratedMap.Text = "Generated Map";
			_radioGeneratedMap.Id = "_radioGeneratedMap";

			var verticalStackPanel1 = new VerticalStackPanel();
			verticalStackPanel1.Widgets.Add(_radioSingleTileMap);
			verticalStackPanel1.Widgets.Add(_radioGeneratedMap);

			
			Title = "New Map";
			Left = 467;
			Top = 191;
			Content = verticalStackPanel1;
		}

		
		public RadioButton _radioSingleTileMap;
		public RadioButton _radioGeneratedMap;
	}
}