/* Generated by MyraPad at 23.10.2019 23:08:53 */
using Myra.Graphics2D.UI;

#if !XENKO
using Microsoft.Xna.Framework;
#else
using Xenko.Core.Mathematics;
#endif

namespace Wanderers.MapEditor.UI
{
	partial class NewGeneratedMapDialog: Dialog
	{
		private void BuildUI()
		{
			var label1 = new Label();
			label1.Text = "Id:";

			_textId = new TextBox();
			_textId.Text = "";
			_textId.Id = "_textId";
			_textId.GridColumn = 1;

			var label2 = new Label();
			label2.Text = "Type:";
			label2.GridRow = 1;

			_comboGenerator = new ComboBox();
			_comboGenerator.Id = "_comboGenerator";
			_comboGenerator.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Stretch;
			_comboGenerator.GridColumn = 1;
			_comboGenerator.GridRow = 1;

			var grid1 = new Grid();
			grid1.ColumnSpacing = 8;
			grid1.RowSpacing = 8;
			grid1.DefaultRowProportion = new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Auto,
			};
			grid1.ColumnsProportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Auto,
			});
			grid1.ColumnsProportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Fill,
			});
			grid1.Widgets.Add(label1);
			grid1.Widgets.Add(_textId);
			grid1.Widgets.Add(label2);
			grid1.Widgets.Add(_comboGenerator);

			
			Title = "New Generated Map";
			Left = 439;
			Top = 187;
			Content = grid1;
		}

		
		public TextBox _textId;
		public ComboBox _comboGenerator;
	}
}