/* Generated by MyraPad at 17.10.2019 22:31:54 */
using Myra.Graphics2D.UI;

#if !XENKO
using Microsoft.Xna.Framework;
#else
using Xenko.Core.Mathematics;
#endif

namespace Wanderers.MapEditor.UI
{
	partial class ResizeMapDialog: Dialog
	{
		private void BuildUI()
		{
			var label1 = new Label();
			label1.Text = "Width:";
			label1.Wrap = true;

			_spinWidth = new SpinButton();
			_spinWidth.Maximum = 1024;
			_spinWidth.Minimum = 1;
			_spinWidth.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Stretch;
			_spinWidth.Value = 48;
			_spinWidth.Integer = true;
			_spinWidth.Id = "_spinWidth";
			_spinWidth.GridColumn = 1;

			var label2 = new Label();
			label2.Text = "Height:";
			label2.Wrap = true;
			label2.GridRow = 1;

			_spinHeight = new SpinButton();
			_spinHeight.Maximum = 1024;
			_spinHeight.Minimum = 1;
			_spinHeight.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Stretch;
			_spinHeight.Value = 48;
			_spinHeight.Integer = true;
			_spinHeight.Id = "_spinHeight";
			_spinHeight.GridColumn = 1;
			_spinHeight.GridRow = 1;

			var label3 = new Label();
			label3.Text = "Filler:";
			label3.Wrap = true;
			label3.GridRow = 2;

			_comboFiller = new ComboBox();
			_comboFiller.Id = "_comboFiller";
			_comboFiller.GridColumn = 1;
			_comboFiller.GridRow = 2;

			Root = new Grid();
			Root.ColumnSpacing = 8;
			Root.RowSpacing = 8;
			Root.DefaultRowProportion = new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Auto,
			};
			Root.ColumnsProportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Auto,
			});
			Root.ColumnsProportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Fill,
			});
			Root.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Right;
			Root.Id = "Root";
			Root.Widgets.Add(label1);
			Root.Widgets.Add(_spinWidth);
			Root.Widgets.Add(label2);
			Root.Widgets.Add(_spinHeight);
			Root.Widgets.Add(label3);
			Root.Widgets.Add(_comboFiller);

			
			Title = "Resize Map";
			Left = 449;
			Top = 170;
			Width = 150;
			Content = Root;
		}

		
		public SpinButton _spinWidth;
		public SpinButton _spinHeight;
		public ComboBox _comboFiller;
		public Grid Root;
	}
}