/* Generated by Myra UI Editor at 26.02.2019 0:03:49 */
using Microsoft.Xna.Framework;
using Myra.Graphics2D.UI;

namespace Wanderers.MapEditor.UI
{
	partial class ResizeMapDialog
	{
		private void BuildUI()
		{
			var textBlock1 = new TextBlock();
			textBlock1.Text = "Width:";
			textBlock1.Wrap = true;

			_spinWidth = new SpinButton();
			_spinWidth.Maximum = 1024;
			_spinWidth.Minimum = 1;
			_spinWidth.Value = 48;
			_spinWidth.Integer = true;
			_spinWidth.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Stretch;
			_spinWidth.Id = "_spinWidth";
			_spinWidth.GridColumn = 1;

			var textBlock2 = new TextBlock();
			textBlock2.Text = "Height:";
			textBlock2.Wrap = true;
			textBlock2.GridRow = 1;

			_spinHeight = new SpinButton();
			_spinHeight.Maximum = 1024;
			_spinHeight.Minimum = 1;
			_spinHeight.Value = 48;
			_spinHeight.Integer = true;
			_spinHeight.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Stretch;
			_spinHeight.Id = "_spinHeight";
			_spinHeight.GridColumn = 1;
			_spinHeight.GridRow = 1;

			var textBlock3 = new TextBlock();
			textBlock3.Text = "Filler:";
			textBlock3.Wrap = true;
			textBlock3.GridRow = 2;

			_comboFiller = new ComboBox();
			_comboFiller.Id = "_comboFiller";
			_comboFiller.GridColumn = 1;
			_comboFiller.GridRow = 2;

			Root = new Grid();
			Root.ColumnSpacing = 8;
			Root.RowSpacing = 8;
			Root.ColumnsProportions.Add(new Grid.Proportion());
			Root.ColumnsProportions.Add(new Grid.Proportion
			{
				Type = Myra.Graphics2D.UI.Grid.ProportionType.Fill,
			});
			Root.RowsProportions.Add(new Grid.Proportion());
			Root.RowsProportions.Add(new Grid.Proportion());
			Root.RowsProportions.Add(new Grid.Proportion());
			Root.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Right;
			Root.Id = "Root";
			Root.GridRow = 1;
			Root.Widgets.Add(textBlock1);
			Root.Widgets.Add(_spinWidth);
			Root.Widgets.Add(textBlock2);
			Root.Widgets.Add(_spinHeight);
			Root.Widgets.Add(textBlock3);
			Root.Widgets.Add(_comboFiller);

			
			Title = "Resize Map";
			Left = 373;
			Top = 377;
			Width = 150;
			Content = Root;
		}

		
		public SpinButton _spinWidth;
		public SpinButton _spinHeight;
		public ComboBox _comboFiller;
		public Grid Root;
	}
}