/* Generated by Myra UI Editor at 26.02.2019 0:04:30 */
using Microsoft.Xna.Framework;
using Myra.Graphics2D.UI;

namespace Wanderers.MapEditor.UI
{
	partial class StudioWidget
	{
		private void BuildUI()
		{
			_openMenuItem = new MenuItem();
			_openMenuItem.Id = "_openMenuItem";
			_openMenuItem.Text = "&Open...";

			_saveMenuItem = new MenuItem();
			_saveMenuItem.Id = "_saveMenuItem";
			_saveMenuItem.Text = "&Save";

			_saveAsMenuItem = new MenuItem();
			_saveAsMenuItem.Id = "_saveAsMenuItem";
			_saveAsMenuItem.Text = "Save &As";

			var menuSeparator1 = new MenuSeparator();

			_resizeMenuItem = new MenuItem();
			_resizeMenuItem.Id = "_resizeMenuItem";
			_resizeMenuItem.Text = "&Resize Map";

			_reloadModuleMenuItem = new MenuItem();
			_reloadModuleMenuItem.Id = "_reloadModuleMenuItem";
			_reloadModuleMenuItem.Text = "Reload &Module";

			var menuSeparator2 = new MenuSeparator();

			_debugOptionsMenuItem = new MenuItem();
			_debugOptionsMenuItem.Id = "_debugOptionsMenuItem";
			_debugOptionsMenuItem.Text = "&UI Debug Options";

			var menuSeparator3 = new MenuSeparator();

			_quitMenuItem = new MenuItem();
			_quitMenuItem.Id = "_quitMenuItem";
			_quitMenuItem.Text = "&Quit";

			var menuItem1 = new MenuItem();
			menuItem1.Id = "";
			menuItem1.Text = "&File";
			menuItem1.Items.Add(_openMenuItem);
			menuItem1.Items.Add(_saveMenuItem);
			menuItem1.Items.Add(_saveAsMenuItem);
			menuItem1.Items.Add(menuSeparator1);
			menuItem1.Items.Add(_resizeMenuItem);
			menuItem1.Items.Add(_reloadModuleMenuItem);
			menuItem1.Items.Add(menuSeparator2);
			menuItem1.Items.Add(_debugOptionsMenuItem);
			menuItem1.Items.Add(menuSeparator3);
			menuItem1.Items.Add(_quitMenuItem);

			_aboutMenuItem = new MenuItem();
			_aboutMenuItem.Id = "_aboutMenuItem";
			_aboutMenuItem.Text = "&About";

			var menuItem2 = new MenuItem();
			menuItem2.Id = "";
			menuItem2.Text = "&Help";
			menuItem2.Items.Add(_aboutMenuItem);

			_mainMenu = new HorizontalMenu();
			_mainMenu.VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Stretch;
			_mainMenu.Id = "_mainMenu";
			_mainMenu.Items.Add(menuItem1);
			_mainMenu.Items.Add(menuItem2);

			_textPosition = new TextBlock();
			_textPosition.Text = "";
			_textPosition.Id = "_textPosition";
			_textPosition.GridRow = 1;

			_leftContainer = new Grid();
			_leftContainer.RowsProportions.Add(new Grid.Proportion
			{
				Type = Myra.Graphics2D.UI.Grid.ProportionType.Fill,
			});
			_leftContainer.RowsProportions.Add(new Grid.Proportion());
			_leftContainer.Id = "_leftContainer";
			_leftContainer.Widgets.Add(_textPosition);

			_mapViewerContainer = new Panel();
			_mapViewerContainer.Id = "_mapViewerContainer";

			_tilesItem = new ListItem();
			_tilesItem.Id = "_tilesItem";
			_tilesItem.Text = "Tiles";

			_creaturesItem = new ListItem();
			_creaturesItem.Id = "_creaturesItem";
			_creaturesItem.Text = "Creatures";

			_comboItemTypes = new ComboBox();
			_comboItemTypes.Id = "_comboItemTypes";
			_comboItemTypes.Items.Add(_tilesItem);
			_comboItemTypes.Items.Add(_creaturesItem);

			var listItem1 = new ListItem();
			listItem1.Id = "";
			listItem1.Text = "testTile1";

			var listItem2 = new ListItem();
			listItem2.Id = "";
			listItem2.Text = "testTile2";

			_listBoxItems = new ListBox();
			_listBoxItems.SelectionMode = Myra.Graphics2D.UI.SelectionMode.Single;
			_listBoxItems.Id = "_listBoxItems";
			_listBoxItems.GridRow = 1;
			_listBoxItems.Items.Add(listItem1);
			_listBoxItems.Items.Add(listItem2);

			var grid1 = new Grid();
			grid1.RowsProportions.Add(new Grid.Proportion());
			grid1.RowsProportions.Add(new Grid.Proportion());
			grid1.GridRow = 2;
			grid1.Widgets.Add(_comboItemTypes);
			grid1.Widgets.Add(_listBoxItems);

			var verticalSplitPane1 = new VerticalSplitPane();
			verticalSplitPane1.GridColumn = 2;
			verticalSplitPane1.GridRow = 1;
			verticalSplitPane1.Widgets.Add(_mapViewerContainer);
			verticalSplitPane1.Widgets.Add(grid1);

			_topSplitPane = new HorizontalSplitPane();
			_topSplitPane.Id = "_topSplitPane";
			_topSplitPane.GridRow = 1;
			_topSplitPane.Widgets.Add(_leftContainer);
			_topSplitPane.Widgets.Add(verticalSplitPane1);

			
			RowsProportions.Add(new Grid.Proportion());
			RowsProportions.Add(new Grid.Proportion
			{
				Type = Myra.Graphics2D.UI.Grid.ProportionType.Fill,
			});
			Id = "Root";
			Widgets.Add(_mainMenu);
			Widgets.Add(_topSplitPane);
		}

		
		public MenuItem _openMenuItem;
		public MenuItem _saveMenuItem;
		public MenuItem _saveAsMenuItem;
		public MenuItem _resizeMenuItem;
		public MenuItem _reloadModuleMenuItem;
		public MenuItem _debugOptionsMenuItem;
		public MenuItem _quitMenuItem;
		public MenuItem _aboutMenuItem;
		public HorizontalMenu _mainMenu;
		public TextBlock _textPosition;
		public Grid _leftContainer;
		public Panel _mapViewerContainer;
		public ListItem _tilesItem;
		public ListItem _creaturesItem;
		public ComboBox _comboItemTypes;
		public ListBox _listBoxItems;
		public HorizontalSplitPane _topSplitPane;
	}
}