/* Generated by MyraPad at 11/14/2023 11:58:56 AM */
using Myra;
using Myra.Graphics2D;
using Myra.Graphics2D.TextureAtlases;
using Myra.Graphics2D.UI;
using Myra.Graphics2D.Brushes;
using Myra.Graphics2D.UI.Properties;
using FontStashSharp.RichText;
using AssetManagementBase;

#if STRIDE
using Stride.Core.Mathematics;
#elif PLATFORM_AGNOSTIC
using System.Drawing;
using System.Numerics;
using Color = FontStashSharp.FSColor;
#else
// MonoGame/FNA
using Microsoft.Xna.Framework;
using Microsoft.Xna.Framework.Graphics;
#endif

namespace Jord.UI
{
	partial class CharacterWindow: Window
	{
		private void BuildUI()
		{
			_tabItemStats = new TabItem();
			_tabItemStats.Text = "Stats";
			_tabItemStats.Content = null;
			_tabItemStats.Id = "_tabItemStats";

			_tabItemInventory = new TabItem();
			_tabItemInventory.Text = "Inventory";
			_tabItemInventory.Content = null;
			_tabItemInventory.Id = "_tabItemInventory";

			_tabControlMain = new TabControl();
			_tabControlMain.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Stretch;
			_tabControlMain.VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Stretch;
			_tabControlMain.ClipToBounds = true;
			_tabControlMain.Id = "_tabControlMain";
			_tabControlMain.Items.Add(_tabItemStats);
			_tabControlMain.Items.Add(_tabItemInventory);

			
			Title = "rds, Warrior, 11, 100k/150k";
			Width = 1200;
			Height = 800;
			Content = _tabControlMain;
		}

		
		public TabItem _tabItemStats;
		public TabItem _tabItemInventory;
		public TabControl _tabControlMain;
	}
}
