/* Generated by MyraPad at 11/12/2023 5:36:04 AM */
using Myra;
using Myra.Graphics2D;
using Myra.Graphics2D.TextureAtlases;
using Myra.Graphics2D.UI;
using Myra.Graphics2D.Brushes;
using Myra.Graphics2D.UI.Properties;
using FontStashSharp.RichText;
using AssetManagementBase;

#if STRIDE
using Stride.Core.Mathematics;
#elif PLATFORM_AGNOSTIC
using System.Drawing;
using System.Numerics;
using Color = FontStashSharp.FSColor;
#else
// MonoGame/FNA
using Microsoft.Xna.Framework;
using Microsoft.Xna.Framework.Graphics;
#endif

namespace Jord.UI
{
	partial class CharacterImage: Grid
	{
		private void BuildUI()
		{
			_textName = new Label();
			_textName.Text = "Henry";
			_textName.Wrap = true;
			_textName.Id = "_textName";

			var label1 = new Label();
			label1.Text = "HP:";
			label1.Wrap = true;

			var label2 = new Label();
			label2.Text = "IP:";
			label2.Wrap = true;
			Grid.SetRow(label2, 1);

			_textHP = new Label();
			_textHP.Text = "100/100";
			_textHP.Wrap = true;
			_textHP.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Center;
			_textHP.Id = "_textHP";
			Grid.SetColumn(_textHP, 1);

			_textIP = new Label();
			_textIP.Text = "100/100";
			_textIP.Wrap = true;
			_textIP.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Center;
			_textIP.Id = "_textIP";
			Grid.SetColumn(_textIP, 1);
			Grid.SetRow(_textIP, 1);

			var grid1 = new Grid();
			grid1.RowSpacing = 4;
			grid1.DefaultRowProportion = new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Auto,
			};
			grid1.ColumnsProportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Auto,
			});
			grid1.ColumnsProportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Fill,
			});
			Grid.SetRow(grid1, 2);
			grid1.Widgets.Add(label1);
			grid1.Widgets.Add(label2);
			grid1.Widgets.Add(_textHP);
			grid1.Widgets.Add(_textIP);

			
			ShowGridLines = true;
			RowSpacing = 4;
			RowsProportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Auto,
			});
			RowsProportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Fill,
				Value = 6,
			});
			RowsProportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Auto,
			});
			HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Left;
			VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Top;
			Width = 200;
			Height = 300;
			Id = "Root";
			Widgets.Add(_textName);
			Widgets.Add(grid1);
		}

		
		public Label _textName;
		public Label _textHP;
		public Label _textIP;
	}
}
