/* Generated by MyraPad at 2/18/2023 11:00:36 PM */
using Myra;
using Myra.Graphics2D;
using Myra.Graphics2D.TextureAtlases;
using Myra.Graphics2D.UI;
using Myra.Graphics2D.Brushes;
using Myra.Graphics2D.UI.Properties;
using FontStashSharp.RichText;
using Microsoft.Xna.Framework;
using Microsoft.Xna.Framework.Graphics;

namespace Jord.UI
{
	partial class CharacterWindow: Window
	{
		private void BuildUI()
		{
			var textButton1 = new TextButton();
			textButton1.Text = "Base Melee";
			textButton1.Toggleable = true;

			var horizontalStackPanel1 = new HorizontalStackPanel();
			horizontalStackPanel1.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Center;
			horizontalStackPanel1.Widgets.Add(textButton1);

			var panel1 = new Panel();
			panel1.Height = 24;

			var textButton2 = new TextButton();
			textButton2.Text = "One-Handed Weapons";
			textButton2.Toggleable = true;

			var textButton3 = new TextButton();
			textButton3.Text = "Two-Handed Weapons";
			textButton3.Toggleable = true;

			var textButton4 = new TextButton();
			textButton4.Text = "Dual Wielding";
			textButton4.Toggleable = true;

			var textButton5 = new TextButton();
			textButton5.Text = "Storm of Steel";
			textButton5.Toggleable = true;

			var horizontalStackPanel2 = new HorizontalStackPanel();
			horizontalStackPanel2.Spacing = 8;
			horizontalStackPanel2.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Center;
			horizontalStackPanel2.Widgets.Add(textButton2);
			horizontalStackPanel2.Widgets.Add(textButton3);
			horizontalStackPanel2.Widgets.Add(textButton4);
			horizontalStackPanel2.Widgets.Add(textButton5);

			var verticalStackPanel1 = new VerticalStackPanel();
			verticalStackPanel1.Spacing = 8;
			verticalStackPanel1.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Center;
			verticalStackPanel1.Widgets.Add(horizontalStackPanel1);
			verticalStackPanel1.Widgets.Add(panel1);
			verticalStackPanel1.Widgets.Add(horizontalStackPanel2);

			_tabItemMelee = new TabItem();
			_tabItemMelee.Text = "Melee";
			_tabItemMelee.ContentVerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Stretch;
			_tabItemMelee.Height = null;
			_tabItemMelee.Id = "_tabItemMelee";
			_tabItemMelee.Content = verticalStackPanel1;

			_tabItemRestoration = new TabItem();
			_tabItemRestoration.Text = "Restoration";
			_tabItemRestoration.Content = null;
			_tabItemRestoration.ContentVerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Stretch;
			_tabItemRestoration.Height = null;
			_tabItemRestoration.Id = "_tabItemRestoration";

			_tabControlMain = new TabControl();
			_tabControlMain.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Stretch;
			_tabControlMain.VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Stretch;
			_tabControlMain.Id = "_tabControlMain";
			_tabControlMain.Items.Add(_tabItemMelee);
			_tabControlMain.Items.Add(_tabItemRestoration);

			_labelPerkPoints = new Label();
			_labelPerkPoints.Text = "Perk Points Left: 2";
			_labelPerkPoints.Id = "_labelPerkPoints";

			var verticalStackPanel2 = new VerticalStackPanel();
			verticalStackPanel2.Spacing = 4;
			verticalStackPanel2.Proportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Fill,
			});
			verticalStackPanel2.Proportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Auto,
			});
			verticalStackPanel2.Widgets.Add(_tabControlMain);
			verticalStackPanel2.Widgets.Add(_labelPerkPoints);

			
			Title = "rds, Warrior, 11, 100k/150k";
			Left = 608;
			Top = 181;
			Width = 700;
			Height = 300;
			Content = verticalStackPanel2;
		}

		
		public TabItem _tabItemMelee;
		public TabItem _tabItemRestoration;
		public TabControl _tabControlMain;
		public Label _labelPerkPoints;
	}
}
