/* Generated by MyraPad at 11/13/2023 12:29:19 AM */
using Myra;
using Myra.Graphics2D;
using Myra.Graphics2D.TextureAtlases;
using Myra.Graphics2D.UI;
using Myra.Graphics2D.Brushes;
using Myra.Graphics2D.UI.Properties;
using FontStashSharp.RichText;
using AssetManagementBase;

#if STRIDE
using Stride.Core.Mathematics;
#elif PLATFORM_AGNOSTIC
using System.Drawing;
using System.Numerics;
using Color = FontStashSharp.FSColor;
#else
// MonoGame/FNA
using Microsoft.Xna.Framework;
using Microsoft.Xna.Framework.Graphics;
#endif

namespace Jord.UI
{
	partial class CharacterPerksPanel: VerticalStackPanel
	{
		private void BuildUI()
		{
			var label1 = new Label();
			label1.Text = "Base Melee";

			var toggleButton1 = new ToggleButton();
			toggleButton1.Content = label1;

			var horizontalStackPanel1 = new HorizontalStackPanel();
			horizontalStackPanel1.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Center;
			horizontalStackPanel1.Widgets.Add(toggleButton1);

			var panel1 = new Panel();
			panel1.Height = 24;

			var horizontalStackPanel2 = new HorizontalStackPanel();
			horizontalStackPanel2.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Center;

			var verticalStackPanel1 = new VerticalStackPanel();
			verticalStackPanel1.Spacing = 8;
			verticalStackPanel1.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Center;
			verticalStackPanel1.Widgets.Add(horizontalStackPanel1);
			verticalStackPanel1.Widgets.Add(panel1);
			verticalStackPanel1.Widgets.Add(horizontalStackPanel2);

			_tabItemMelee = new TabItem();
			_tabItemMelee.Text = "Melee";
			_tabItemMelee.Id = "_tabItemMelee";
			_tabItemMelee.Content = verticalStackPanel1;

			_tabItemRestoration = new TabItem();
			_tabItemRestoration.Text = "Restoration";
			_tabItemRestoration.Content = null;
			_tabItemRestoration.Id = "_tabItemRestoration";

			_tabControlPerks = new TabControl();
			_tabControlPerks.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Stretch;
			_tabControlPerks.VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Stretch;
			_tabControlPerks.TabSelectorPosition = Myra.Graphics2D.UI.TabSelectorPosition.Left;
			_tabControlPerks.ClipToBounds = true;
			_tabControlPerks.Id = "_tabControlPerks";
			StackPanel.SetProportionType(_tabControlPerks, Myra.Graphics2D.UI.ProportionType.Fill);
			_tabControlPerks.Items.Add(_tabItemMelee);
			_tabControlPerks.Items.Add(_tabItemRestoration);

			_labelPerkPoints = new Label();
			_labelPerkPoints.Text = "Perk Points Left: 2";
			_labelPerkPoints.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Right;
			_labelPerkPoints.Id = "_labelPerkPoints";

			
			Spacing = 4;
			Widgets.Add(_tabControlPerks);
			Widgets.Add(_labelPerkPoints);
		}

		
		public TabItem _tabItemMelee;
		public TabItem _tabItemRestoration;
		public TabControl _tabControlPerks;
		public Label _labelPerkPoints;
	}
}
