/* Generated by MyraPad at 11/15/2023 4:49:19 AM */
using Myra;
using Myra.Graphics2D;
using Myra.Graphics2D.TextureAtlases;
using Myra.Graphics2D.UI;
using Myra.Graphics2D.Brushes;
using Myra.Graphics2D.UI.Properties;
using FontStashSharp.RichText;
using AssetManagementBase;

#if STRIDE
using Stride.Core.Mathematics;
#elif PLATFORM_AGNOSTIC
using System.Drawing;
using System.Numerics;
using Color = FontStashSharp.FSColor;
#else
// MonoGame/FNA
using Microsoft.Xna.Framework;
using Microsoft.Xna.Framework.Graphics;
#endif

namespace Jord.UI
{
	partial class CharacterStatsPanel: Grid
	{
		private void BuildUI()
		{
			var label1 = new Label();
			label1.Text = "Melee:";

			_labelMelee = new Label();
			_labelMelee.Text = "30";
			_labelMelee.Id = "_labelMelee";
			Grid.SetColumn(_labelMelee, 1);

			var label2 = new Label();
			label2.Text = "Armor:";
			Grid.SetRow(label2, 1);

			_labelArmor = new Label();
			_labelArmor.Text = "30";
			_labelArmor.Id = "_labelArmor";
			Grid.SetColumn(_labelArmor, 1);
			Grid.SetRow(_labelArmor, 1);

			var label3 = new Label();
			label3.Text = "Evasion:";
			Grid.SetRow(label3, 2);

			_labelEvasion = new Label();
			_labelEvasion.Text = "30";
			_labelEvasion.Id = "_labelEvasion";
			Grid.SetColumn(_labelEvasion, 1);
			Grid.SetRow(_labelEvasion, 2);

			var label4 = new Label();
			label4.Text = "Blocking:";
			Grid.SetRow(label4, 3);

			_labelBlocking = new Label();
			_labelBlocking.Text = "30";
			_labelBlocking.Id = "_labelBlocking";
			Grid.SetColumn(_labelBlocking, 1);
			Grid.SetRow(_labelBlocking, 3);

			var label5 = new Label();
			label5.Text = "Attacks:";
			Grid.SetRow(label5, 4);

			_labelAttacks = new Label();
			_labelAttacks.Text = "30";
			_labelAttacks.Id = "_labelAttacks";
			Grid.SetColumn(_labelAttacks, 1);
			Grid.SetRow(_labelAttacks, 4);

			
			ColumnSpacing = 8;
			RowSpacing = 8;
			DefaultColumnProportion = new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Auto,
			};
			DefaultRowProportion = new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Auto,
			};
			Widgets.Add(label1);
			Widgets.Add(_labelMelee);
			Widgets.Add(label2);
			Widgets.Add(_labelArmor);
			Widgets.Add(label3);
			Widgets.Add(_labelEvasion);
			Widgets.Add(label4);
			Widgets.Add(_labelBlocking);
			Widgets.Add(label5);
			Widgets.Add(_labelAttacks);
		}

		
		public Label _labelMelee;
		public Label _labelArmor;
		public Label _labelEvasion;
		public Label _labelBlocking;
		public Label _labelAttacks;
	}
}
