/* Generated by MyraPad at 12/7/2020 1:11:37 AM */
using Myra;
using Myra.Graphics2D;
using Myra.Graphics2D.TextureAtlases;
using Myra.Graphics2D.UI;
using Myra.Graphics2D.Brushes;

#if !STRIDE
using Microsoft.Xna.Framework;
using Microsoft.Xna.Framework.Graphics;
#else
using Stride.Core.Mathematics;
#endif

namespace Jord.UI
{
	partial class CraftingWindow: Window
	{
		private void BuildUI()
		{
			var horizontalSeparator1 = new HorizontalSeparator();

			var listItem1 = new ListItem();
			listItem1.Text = "leather jacket";
			listItem1.Color = new Color
			{
				B = 140,
				G = 140,
				R = 140,
				A = 255,
			};

			var listItem2 = new ListItem();
			listItem2.Text = "leather pants";
			listItem2.Color = new Color
			{
				B = 140,
				G = 140,
				R = 140,
				A = 255,
			};

			var listItem3 = new ListItem();
			listItem3.Text = "leather sleeves";

			var listItem4 = new ListItem();
			listItem4.Text = "leather cap";

			var listItem5 = new ListItem();
			listItem5.Text = "leather gloves";

			var listItem6 = new ListItem();
			listItem6.Text = "leather boots";

			_listBoxRecipes = new ListBox();
			_listBoxRecipes.Width = 200;
			_listBoxRecipes.VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Stretch;
			_listBoxRecipes.Id = "_listBoxRecipes";
			_listBoxRecipes.Items.Add(listItem1);
			_listBoxRecipes.Items.Add(listItem2);
			_listBoxRecipes.Items.Add(listItem3);
			_listBoxRecipes.Items.Add(listItem4);
			_listBoxRecipes.Items.Add(listItem5);
			_listBoxRecipes.Items.Add(listItem6);

			var verticalSeparator1 = new VerticalSeparator();

			_labelDescription = new Label();
			_labelDescription.Text = "armor, ac: 4";
			_labelDescription.Wrap = true;
			_labelDescription.Width = 200;
			_labelDescription.Id = "_labelDescription";

			var horizontalSeparator2 = new HorizontalSeparator();

			_labelRequires = new Label();
			_labelRequires.Text = "2 Leather (3), Iron Ingot (2), 3 Steel Ingot (4)";
			_labelRequires.Wrap = true;
			_labelRequires.Width = 200;
			_labelRequires.Id = "_labelRequires";

			var verticalStackPanel1 = new VerticalStackPanel();
			verticalStackPanel1.Proportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Part,
			});
			verticalStackPanel1.Proportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Auto,
			});
			verticalStackPanel1.Proportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Part,
			});
			verticalStackPanel1.Widgets.Add(_labelDescription);
			verticalStackPanel1.Widgets.Add(horizontalSeparator2);
			verticalStackPanel1.Widgets.Add(_labelRequires);

			var horizontalStackPanel1 = new HorizontalStackPanel();
			horizontalStackPanel1.Widgets.Add(_listBoxRecipes);
			horizontalStackPanel1.Widgets.Add(verticalSeparator1);
			horizontalStackPanel1.Widgets.Add(verticalStackPanel1);

			var horizontalSeparator3 = new HorizontalSeparator();

			_buttonCreate = new TextButton();
			_buttonCreate.Text = "\\c[green]C\\c[white]reate";
			_buttonCreate.Width = 120;
			_buttonCreate.Id = "_buttonCreate";

			var horizontalStackPanel2 = new HorizontalStackPanel();
			horizontalStackPanel2.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Right;
			horizontalStackPanel2.Widgets.Add(_buttonCreate);

			var verticalStackPanel2 = new VerticalStackPanel();
			verticalStackPanel2.Proportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Auto,
			});
			verticalStackPanel2.Proportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Fill,
			});
			verticalStackPanel2.Widgets.Add(horizontalSeparator1);
			verticalStackPanel2.Widgets.Add(horizontalStackPanel1);
			verticalStackPanel2.Widgets.Add(horizontalSeparator3);
			verticalStackPanel2.Widgets.Add(horizontalStackPanel2);

			
			Title = "Crafting Bench";
			Left = 471;
			Top = 20;
			Height = 500;
			Content = verticalStackPanel2;
		}

		
		public ListBox _listBoxRecipes;
		public Label _labelDescription;
		public Label _labelRequires;
		public TextButton _buttonCreate;
	}
}
