/* Generated by MyraPad at 12/7/2020 1:04:58 AM */
using Jord.Core.Items;
using Microsoft.Xna.Framework;
using Myra.Graphics2D.UI;
using System.Text;

namespace Jord.UI
{
	public partial class CraftingWindow
	{
		public CraftingWindow()
		{
			BuildUI();

			_listBoxRecipes.AcceptsKeyboardFocus = false;

			_listBoxRecipes.SelectedIndexChanged += _listBoxRecipes_SelectedIndexChanged;
			_buttonCreate.Click += _buttonCreate_Click;

			Rebuild();
		}

		private void _buttonCreate_Click(object sender, System.EventArgs e)
		{
			var lastIndex = _listBoxRecipes.SelectedIndex.Value;

			// Remove components from inventory
			var item = (BaseItemInfo)_listBoxRecipes.SelectedItem.Tag;
			var player = TJ.Player;

			foreach (var component in item.Crafting.Items)
			{
				player.Inventory.Add(component.Item, -component.Quantity);
			}

			// Add crafting result
			player.Inventory.Add(new Item(item), 1);

			Rebuild();

			if (lastIndex < _listBoxRecipes.Items.Count)
			{
				_listBoxRecipes.SelectedIndex = lastIndex;
			}
		}

		private void _listBoxRecipes_SelectedIndexChanged(object sender, System.EventArgs e)
		{
			_labelDescription.Text = string.Empty;
			_labelRequires.Text = string.Empty;

			if (_listBoxRecipes.SelectedIndex == null)
			{
				return;
			}

			var item = (BaseItemInfo)_listBoxRecipes.SelectedItem.Tag;

			_labelDescription.Text = "Description: " + item.BuildDescription();

			var sb = new StringBuilder();

			sb.Append("Requires: ");

			for(var i = 0; i < item.Crafting.Items.Count; ++i)
			{
				var component = item.Crafting.Items[i];

				if (component.Quantity > 1)
				{
					sb.Append(component.Quantity);
					sb.Append(" ");
				}

				sb.Append(component.Item.Info.Name);
				sb.Append(" (");

				var quantity = 0;
				foreach (var playerItem in TJ.Player.Inventory.Items)
				{
					if (component.Item == playerItem.Item)
					{
						quantity = playerItem.Quantity;
						break;
					}
				}

				sb.Append(quantity);
				sb.Append(")");

				if (i < item.Crafting.Items.Count - 1)
				{
					sb.Append(", ");
				}
			}

			_labelRequires.Text = sb.ToString();
			UpdateButtons();
		}

		private void Rebuild()
		{
			_listBoxRecipes.Items.Clear();
			_labelDescription.Text = string.Empty;
			_labelRequires.Text = string.Empty;

			var inventory = TJ.Player.Inventory;
			foreach (var pair in TJ.Module.ItemInfos)
			{
				var crafting = pair.Value.Crafting;
				if (crafting != null && crafting.Count > 0)
				{
					var color = inventory.Contains(crafting) ? Color.White : Color.Gray;

					var listItem = new ListItem
					{
						Color = color,
						Text = pair.Value.Name,
						Tag = pair.Value
					};

					_listBoxRecipes.Items.Add(listItem);
				}
			}

			UpdateButtons();
		}

		private void UpdateButtons()
		{
			BaseItemInfo item = null;

			if (_listBoxRecipes.SelectedIndex != null)
			{
				item = (BaseItemInfo)_listBoxRecipes.SelectedItem.Tag;
			}

			_buttonCreate.Enabled = item != null && TJ.Player.Inventory.Contains(item.Crafting);
		}
	}
}