/* Generated by MyraPad at 11/12/2023 4:52:26 AM */
using Myra;
using Myra.Graphics2D;
using Myra.Graphics2D.TextureAtlases;
using Myra.Graphics2D.UI;
using Myra.Graphics2D.Brushes;
using Myra.Graphics2D.UI.Properties;
using FontStashSharp.RichText;
using AssetManagementBase;

#if STRIDE
using Stride.Core.Mathematics;
#elif PLATFORM_AGNOSTIC
using System.Drawing;
using System.Numerics;
using Color = FontStashSharp.FSColor;
#else
// MonoGame/FNA
using Microsoft.Xna.Framework;
using Microsoft.Xna.Framework.Graphics;
#endif

namespace Jord.UI
{
	partial class GameView: Panel
	{
		private void BuildUI()
		{
			_mapViewContainer = new Panel();
			_mapViewContainer.Id = "_mapViewContainer";
			StackPanel.SetProportionType(_mapViewContainer, Myra.Graphics2D.UI.ProportionType.Fill);

			var horizontalSeparator1 = new HorizontalSeparator();

			var label1 = new Label();
			label1.Text = "/c[green]E/c[white]|Use";
			label1.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Center;

			_buttonUse = new Button();
			_buttonUse.Width = 100;
			_buttonUse.Id = "_buttonUse";
			_buttonUse.Content = label1;

			var label2 = new Label();
			label2.Text = "/c[green]C/c[white]haracter";
			label2.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Center;

			_buttonCharacter = new Button();
			_buttonCharacter.Width = 100;
			_buttonCharacter.Id = "_buttonCharacter";
			_buttonCharacter.Content = label2;

			var label3 = new Label();
			label3.Text = "/c[green]I/c[white]nventory";
			label3.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Center;

			_buttonInventory = new Button();
			_buttonInventory.Width = 100;
			_buttonInventory.Id = "_buttonInventory";
			_buttonInventory.Content = label3;

			var label4 = new Label();
			label4.Text = "/c[green]A/c[white]bilities";
			label4.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Center;

			_buttonAbilities = new Button();
			_buttonAbilities.Width = 100;
			_buttonAbilities.Id = "_buttonAbilities";
			_buttonAbilities.Content = label4;

			var horizontalStackPanel1 = new HorizontalStackPanel();
			horizontalStackPanel1.Spacing = 8;
			horizontalStackPanel1.Widgets.Add(_buttonUse);
			horizontalStackPanel1.Widgets.Add(_buttonCharacter);
			horizontalStackPanel1.Widgets.Add(_buttonInventory);
			horizontalStackPanel1.Widgets.Add(_buttonAbilities);

			var verticalStackPanel1 = new VerticalStackPanel();
			StackPanel.SetProportionType(verticalStackPanel1, Myra.Graphics2D.UI.ProportionType.Part);
			StackPanel.SetProportionValue(verticalStackPanel1, 2);
			verticalStackPanel1.Widgets.Add(_mapViewContainer);
			verticalStackPanel1.Widgets.Add(horizontalSeparator1);
			verticalStackPanel1.Widgets.Add(horizontalStackPanel1);

			var verticalSeparator1 = new VerticalSeparator();

			_labelHp = new Label();
			_labelHp.Text = "HP: 50/100";
			_labelHp.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Center;
			_labelHp.Id = "_labelHp";
			StackPanel.SetProportionType(_labelHp, Myra.Graphics2D.UI.ProportionType.Part);

			var verticalSeparator2 = new VerticalSeparator();

			_labelMana = new Label();
			_labelMana.Text = "MA: 50/100";
			_labelMana.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Center;
			_labelMana.Id = "_labelMana";
			StackPanel.SetProportionType(_labelMana, Myra.Graphics2D.UI.ProportionType.Part);

			var verticalSeparator3 = new VerticalSeparator();

			_labelStamina = new Label();
			_labelStamina.Text = "ST: 50/100";
			_labelStamina.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Center;
			_labelStamina.Id = "_labelStamina";
			StackPanel.SetProportionType(_labelStamina, Myra.Graphics2D.UI.ProportionType.Part);

			var horizontalStackPanel2 = new HorizontalStackPanel();
			horizontalStackPanel2.Widgets.Add(_labelHp);
			horizontalStackPanel2.Widgets.Add(verticalSeparator2);
			horizontalStackPanel2.Widgets.Add(_labelMana);
			horizontalStackPanel2.Widgets.Add(verticalSeparator3);
			horizontalStackPanel2.Widgets.Add(_labelStamina);

			var horizontalSeparator2 = new HorizontalSeparator();

			_mapContainer = new Panel();
			_mapContainer.Height = 247;
			_mapContainer.Id = "_mapContainer";

			var horizontalSeparator3 = new HorizontalSeparator();

			_logContainer = new Panel();
			_logContainer.Id = "_logContainer";
			StackPanel.SetProportionType(_logContainer, Myra.Graphics2D.UI.ProportionType.Fill);

			var verticalStackPanel2 = new VerticalStackPanel();
			StackPanel.SetProportionType(verticalStackPanel2, Myra.Graphics2D.UI.ProportionType.Part);
			verticalStackPanel2.Widgets.Add(horizontalStackPanel2);
			verticalStackPanel2.Widgets.Add(horizontalSeparator2);
			verticalStackPanel2.Widgets.Add(_mapContainer);
			verticalStackPanel2.Widgets.Add(horizontalSeparator3);
			verticalStackPanel2.Widgets.Add(_logContainer);

			var horizontalStackPanel3 = new HorizontalStackPanel();
			horizontalStackPanel3.Widgets.Add(verticalStackPanel1);
			horizontalStackPanel3.Widgets.Add(verticalSeparator1);
			horizontalStackPanel3.Widgets.Add(verticalStackPanel2);

			_labelFps = new Label();
			_labelFps.Text = "59.99";
			_labelFps.Id = "_labelFps";

			_panelDebug = new Panel();
			_panelDebug.Id = "_panelDebug";
			_panelDebug.Widgets.Add(_labelFps);

			
			Widgets.Add(horizontalStackPanel3);
			Widgets.Add(_panelDebug);
		}

		
		public Panel _mapViewContainer;
		public Button _buttonUse;
		public Button _buttonCharacter;
		public Button _buttonInventory;
		public Button _buttonAbilities;
		public Label _labelHp;
		public Label _labelMana;
		public Label _labelStamina;
		public Panel _mapContainer;
		public Panel _logContainer;
		public Label _labelFps;
		public Panel _panelDebug;
	}
}
