/* Generated by MyraPad at 4/12/2023 6:17:30 AM */
using Myra;
using Myra.Graphics2D;
using Myra.Graphics2D.TextureAtlases;
using Myra.Graphics2D.UI;
using Myra.Graphics2D.Brushes;
using Myra.Graphics2D.UI.Properties;
using FontStashSharp.RichText;
using Microsoft.Xna.Framework;
using Microsoft.Xna.Framework.Graphics;

namespace Jord.UI
{
	partial class GameView: Panel
	{
		private void BuildUI()
		{
			_mapViewContainer = new Panel();
			_mapViewContainer.Id = "_mapViewContainer";

			var horizontalSeparator1 = new HorizontalSeparator();

			_buttonUse = new TextButton();
			_buttonUse.Text = "/c[green]E/c[white]|Use";
			_buttonUse.Width = 100;
			_buttonUse.Id = "_buttonUse";

			_buttonCharacter = new TextButton();
			_buttonCharacter.Text = "/c[green]C/c[white]haracter";
			_buttonCharacter.Width = 100;
			_buttonCharacter.Id = "_buttonCharacter";

			_buttonInventory = new TextButton();
			_buttonInventory.Text = "/c[green]I/c[white]nventory";
			_buttonInventory.Width = 100;
			_buttonInventory.Id = "_buttonInventory";

			_buttonAbilities = new TextButton();
			_buttonAbilities.Text = "/c[green]A/c[white]bilities";
			_buttonAbilities.Width = 100;
			_buttonAbilities.Id = "_buttonAbilities";

			var horizontalStackPanel1 = new HorizontalStackPanel();
			horizontalStackPanel1.Spacing = 8;
			horizontalStackPanel1.Widgets.Add(_buttonUse);
			horizontalStackPanel1.Widgets.Add(_buttonCharacter);
			horizontalStackPanel1.Widgets.Add(_buttonInventory);
			horizontalStackPanel1.Widgets.Add(_buttonAbilities);

			var verticalStackPanel1 = new VerticalStackPanel();
			verticalStackPanel1.Proportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Fill,
			});
			verticalStackPanel1.Widgets.Add(_mapViewContainer);
			verticalStackPanel1.Widgets.Add(horizontalSeparator1);
			verticalStackPanel1.Widgets.Add(horizontalStackPanel1);

			var verticalSeparator1 = new VerticalSeparator();

			_labelHp = new Label();
			_labelHp.Text = "HP: 50/100";
			_labelHp.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Center;
			_labelHp.Id = "_labelHp";

			var verticalSeparator2 = new VerticalSeparator();

			_labelMana = new Label();
			_labelMana.Text = "MA: 50/100";
			_labelMana.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Center;
			_labelMana.Id = "_labelMana";

			var verticalSeparator3 = new VerticalSeparator();

			_labelStamina = new Label();
			_labelStamina.Text = "ST: 50/100";
			_labelStamina.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Center;
			_labelStamina.Id = "_labelStamina";

			var horizontalStackPanel2 = new HorizontalStackPanel();
			horizontalStackPanel2.Proportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Part,
			});
			horizontalStackPanel2.Proportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Auto,
			});
			horizontalStackPanel2.Proportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Part,
			});
			horizontalStackPanel2.Proportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Auto,
			});
			horizontalStackPanel2.Proportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Part,
			});
			horizontalStackPanel2.Widgets.Add(_labelHp);
			horizontalStackPanel2.Widgets.Add(verticalSeparator2);
			horizontalStackPanel2.Widgets.Add(_labelMana);
			horizontalStackPanel2.Widgets.Add(verticalSeparator3);
			horizontalStackPanel2.Widgets.Add(_labelStamina);

			var horizontalSeparator2 = new HorizontalSeparator();

			_mapContainer = new Panel();
			_mapContainer.Height = 247;
			_mapContainer.Id = "_mapContainer";

			var horizontalSeparator3 = new HorizontalSeparator();

			_logContainer = new Panel();
			_logContainer.Id = "_logContainer";

			var verticalStackPanel2 = new VerticalStackPanel();
			verticalStackPanel2.Proportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Auto,
			});
			verticalStackPanel2.Proportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Auto,
			});
			verticalStackPanel2.Proportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Auto,
			});
			verticalStackPanel2.Proportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Auto,
			});
			verticalStackPanel2.Proportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Fill,
			});
			verticalStackPanel2.Widgets.Add(horizontalStackPanel2);
			verticalStackPanel2.Widgets.Add(horizontalSeparator2);
			verticalStackPanel2.Widgets.Add(_mapContainer);
			verticalStackPanel2.Widgets.Add(horizontalSeparator3);
			verticalStackPanel2.Widgets.Add(_logContainer);

			var horizontalStackPanel3 = new HorizontalStackPanel();
			horizontalStackPanel3.Proportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Part,
				Value = 2,
			});
			horizontalStackPanel3.Proportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Auto,
			});
			horizontalStackPanel3.Proportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Part,
			});
			horizontalStackPanel3.Widgets.Add(verticalStackPanel1);
			horizontalStackPanel3.Widgets.Add(verticalSeparator1);
			horizontalStackPanel3.Widgets.Add(verticalStackPanel2);

			_labelFps = new Label();
			_labelFps.Text = "59.99";
			_labelFps.Id = "_labelFps";

			_panelDebug = new Panel();
			_panelDebug.Id = "_panelDebug";
			_panelDebug.Widgets.Add(_labelFps);

			
			Widgets.Add(horizontalStackPanel3);
			Widgets.Add(_panelDebug);
		}

		
		public Panel _mapViewContainer;
		public TextButton _buttonUse;
		public TextButton _buttonCharacter;
		public TextButton _buttonInventory;
		public TextButton _buttonAbilities;
		public Label _labelHp;
		public Label _labelMana;
		public Label _labelStamina;
		public Panel _mapContainer;
		public Panel _logContainer;
		public Label _labelFps;
		public Panel _panelDebug;
	}
}
