/* Generated by MyraPad at 16.03.2019 1:32:50 */
using Myra.Graphics2D.UI;
using System;
using System.Text;
using Jord.Core;
using Jord.Core.Items;
using Jord.Utils;
using Microsoft.Xna.Framework.Input;

namespace Jord.UI
{
	public partial class InventoryWindow : Window
	{
		private Item SelectedItem
		{
			get
			{
				Item item = null;
				if (_gridEquipment.SelectedRowIndex != null)
				{
					item = TJ.Player.Equipment.Items[_gridEquipment.SelectedRowIndex.Value].Item;
				}
				else if (_gridInventory.SelectedRowIndex != null)
				{
					item = TJ.Player.Inventory.Items[_gridInventory.SelectedRowIndex.Value].Item;
				}

				return item;
			}
		}

		public InventoryWindow()
		{
			BuildUI();

			AcceptsKeyboardFocus = true;

			_gridEquipment.SetGridStyle();
			_gridInventory.SetGridStyle();

			_gridEquipment.HoverIndexChanged += OnEquipmentHoverIndexChanged;
			_gridEquipment.SelectedIndexChanged += OnEquipmentSelectedIndexChanged;

			_gridInventory.HoverIndexChanged += OnInventoryHoverIndexChanged;
			_gridInventory.SelectedIndexChanged += OnInventorySelectedIndexChanged;

			_textDescription.Text = string.Empty;

			_buttonEquip.Click += _buttonEquip_Click;
			_buttonDrop.Click += _buttonDrop_Click;

			Rebuild();
		}

		private void _buttonDrop_Click(object sender, EventArgs e)
		{
			var item = SelectedItem;

			if (_gridEquipment.SelectedRowIndex != null)
			{
				// Remove from equipment
				TJ.Player.Equipment.Remove(_gridEquipment.SelectedRowIndex.Value);
			}
			else if (_gridInventory.SelectedRowIndex != null)
			{
				// Remove from inventory
				TJ.Player.Inventory.Add(item, -1);
			}

			// Drop on tile
			TJ.PlayerTile.Inventory.Add(item, 1);

			Rebuild();
		}

		private void _buttonEquip_Click(object sender, EventArgs e)
		{
			var item = SelectedItem;

			if (_gridEquipment.SelectedRowIndex != null)
			{
				// Remove from equipment
				TJ.Player.Equipment.Remove(_gridEquipment.SelectedRowIndex.Value);

				// Add to inventory
				TJ.Player.Inventory.Add(item, 1);
			}
			else if (_gridInventory.SelectedRowIndex != null)
			{
				// Wear
				TJ.Player.Equipment.Equip(item);

				// Remove from inventory
				TJ.Player.Inventory.Add(item, -1);
			}

			Rebuild();
		}

		private void UpdateButtons()
		{
			_buttonDrop.Enabled = false;
			_buttonEquip.Enabled = false;
			_buttonUse.Enabled = false;

			var item = SelectedItem;
			if (item == null)
			{
				return;
			}

			var asEquip = item.Info as EquipInfo;
			if (asEquip != null)
			{
				if (_gridEquipment.SelectedRowIndex != null)
				{
					_buttonEquip.Text = string.Format(@"Un/c[green]e/c[white]quip");
				}
				else
				{
					_buttonEquip.Text = string.Format(@"/c[green]E/c[white]quip");
				}

				_buttonEquip.Enabled = true;
			}

			_buttonDrop.Enabled = true;
		}

		private void UpdateStats()
		{
			var battle = TJ.Player.Stats.Battle;
			_textAc.Text = "AC: " + battle.ArmorClass.ToString();
			_textHitRoll.Text = "Hit Roll: " + battle.HitRoll;

			var sb = new StringBuilder();

			sb.Append("Attacks: ");
			for (var i = 0; i < battle.Attacks.Length; ++i)
			{
				var attack = battle.Attacks[i];

				sb.Append(attack.MinDamage);
				sb.Append('-');
				sb.Append(attack.MaxDamage);

				if (i < TJ.Player.Stats.Battle.Attacks.Length - 1)
				{
					sb.Append('/');
				}
			}

			_textAttacks.Text = sb.ToString();
			_textGold.Text = "Gold: " + TJ.Player.Inventory.Gold;
		}

		private void Rebuild()
		{
			_gridEquipment.Widgets.Clear();
			_gridEquipment.RowsProportions.Clear();

			foreach (var item in TJ.Player.Equipment.Items)
			{
				var row = _gridEquipment.RowsProportions.Count;

				var textSlot = new Label
				{
					Text = "<" + item.Slot.ToString().ToLower() + ">",
					GridRow = row
				};
				_gridEquipment.Widgets.Add(textSlot);

				if (item.Item != null)
				{
					var textItem = new Label
					{
						Text = item.Item.Info.Name,
						GridColumn = 1,
						GridRow = row
					};

					_gridEquipment.Widgets.Add(textItem);
				}

				_gridEquipment.RowsProportions.Add(new Proportion());
			}

			_gridInventory.Widgets.Clear();
			_gridInventory.RowsProportions.Clear();

			foreach (var item in TJ.Player.Inventory.Items)
			{
				var row = _gridInventory.RowsProportions.Count;

				var textSlot = new Label
				{
					Text = item.ToString(),
					GridRow = row
				};
				_gridInventory.Widgets.Add(textSlot);

				_gridInventory.RowsProportions.Add(new Proportion());
			}

			UpdateStats();
			UpdateButtons();
		}

		private void OnHoverIndexChanged(Grid grid, Item item)
		{
			if (grid.HoverRowIndex == null)
			{
				return;
			}

			_textDescription.Text = item.BuildDescription();
		}

		private void OnInventoryHoverIndexChanged(object sender, EventArgs e)
		{
			if (_gridInventory.HoverRowIndex == null)
			{
				return;
			}

			var item = TJ.Player.Inventory.Items[_gridInventory.HoverRowIndex.Value].Item;
			_textDescription.Text = item.BuildDescription();
		}

		private void OnEquipmentHoverIndexChanged(object sender, EventArgs e)
		{
			if (_gridEquipment.HoverRowIndex == null)
			{
				return;
			}

			var item = TJ.Player.Equipment.Items[_gridEquipment.HoverRowIndex.Value].Item;
			_textDescription.Text = item != null ? item.BuildDescription() : string.Empty;
		}

		private void OnInventorySelectedIndexChanged(object sender, EventArgs e)
		{
			if (_gridInventory.SelectedRowIndex == null)
			{
				return;
			}

			_gridEquipment.SelectedRowIndex = null;

			UpdateButtons();
		}

		private void OnEquipmentSelectedIndexChanged(object sender, EventArgs e)
		{
			if (_gridEquipment.SelectedRowIndex == null)
			{
				return;
			}

			_gridInventory.SelectedRowIndex = null;

			UpdateButtons();
		}

		public override void OnKeyDown(Keys k)
		{
			base.OnKeyDown(k);

			switch (k)
			{
				case Keys.E:
					if (_buttonEquip.Enabled)
					{
						_buttonEquip.DoClick();
					}
					break;
				case Keys.D:
					if (_buttonDrop.Enabled)
					{
						_buttonDrop.DoClick();
					}
					break;
			}
		}
	}
}