/* Generated by MyraPad at 11/12/2023 5:36:41 AM */
using Myra;
using Myra.Graphics2D;
using Myra.Graphics2D.TextureAtlases;
using Myra.Graphics2D.UI;
using Myra.Graphics2D.Brushes;
using Myra.Graphics2D.UI.Properties;
using FontStashSharp.RichText;
using AssetManagementBase;

#if STRIDE
using Stride.Core.Mathematics;
#elif PLATFORM_AGNOSTIC
using System.Drawing;
using System.Numerics;
using Color = FontStashSharp.FSColor;
#else
// MonoGame/FNA
using Microsoft.Xna.Framework;
using Microsoft.Xna.Framework.Graphics;
#endif

namespace Jord.UI
{
	partial class MainMenu: Grid
	{
		private void BuildUI()
		{
			var label1 = new Label();
			label1.Text = "Troubles of Jord";
			label1.TextColor = ColorStorage.CreateColor(255, 128, 64, 255);
			label1.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Center;

			_playItem = new MenuItem();
			_playItem.Text = "Play";
			_playItem.Id = "_playItem";

			_quitMenuItem = new MenuItem();
			_quitMenuItem.Text = "Quit";
			_quitMenuItem.Id = "_quitMenuItem";

			_mainMenu = new VerticalMenu();
			_mainMenu.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Center;
			_mainMenu.VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Center;
			_mainMenu.Width = 200;
			_mainMenu.Id = "_mainMenu";
			_mainMenu.Items.Add(_playItem);
			_mainMenu.Items.Add(_quitMenuItem);

			_textVersion = new Label();
			_textVersion.Text = "Version 1.0";
			_textVersion.TextColor = Color.Lime;
			_textVersion.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Right;
			_textVersion.VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Bottom;
			_textVersion.Id = "_textVersion";

			
			Id = "Root";
			Widgets.Add(label1);
			Widgets.Add(_mainMenu);
			Widgets.Add(_textVersion);
		}

		
		public MenuItem _playItem;
		public MenuItem _quitMenuItem;
		public VerticalMenu _mainMenu;
		public Label _textVersion;
	}
}
