/* Generated by MyraPad at 11/12/2023 5:34:37 AM */
using Myra;
using Myra.Graphics2D;
using Myra.Graphics2D.TextureAtlases;
using Myra.Graphics2D.UI;
using Myra.Graphics2D.Brushes;
using Myra.Graphics2D.UI.Properties;
using FontStashSharp.RichText;
using AssetManagementBase;

#if STRIDE
using Stride.Core.Mathematics;
#elif PLATFORM_AGNOSTIC
using System.Drawing;
using System.Numerics;
using Color = FontStashSharp.FSColor;
#else
// MonoGame/FNA
using Microsoft.Xna.Framework;
using Microsoft.Xna.Framework.Graphics;
#endif

namespace Jord.UI
{
	partial class TakeWindow: Window
	{
		private void BuildUI()
		{
			var label1 = new Label();
			label1.Text = "Iron Ration";

			var label2 = new Label();
			label2.Text = "10";
			Grid.SetColumn(label2, 1);

			var label3 = new Label();
			label3.Text = "Sword";
			Grid.SetRow(label3, 1);

			var label4 = new Label();
			label4.Text = "1";
			Grid.SetColumn(label4, 1);
			Grid.SetRow(label4, 1);

			var label5 = new Label();
			label5.Text = "Rhodochosite";
			Grid.SetRow(label5, 2);

			var label6 = new Label();
			label6.Text = "5";
			Grid.SetColumn(label6, 1);
			Grid.SetRow(label6, 2);

			_gridItems = new Grid();
			_gridItems.ColumnSpacing = 8;
			_gridItems.DefaultRowProportion = new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Auto,
			};
			_gridItems.ColumnsProportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Fill,
				Value = 150,
			});
			_gridItems.ColumnsProportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Auto,
			});
			_gridItems.SelectionBackground = new SolidBrush("#0379FFFF");
			_gridItems.SelectionHoverBackground = new SolidBrush("#666666FF");
			_gridItems.GridSelectionMode = Myra.Graphics2D.UI.GridSelectionMode.Row;
			_gridItems.Id = "_gridItems";
			_gridItems.Widgets.Add(label1);
			_gridItems.Widgets.Add(label2);
			_gridItems.Widgets.Add(label3);
			_gridItems.Widgets.Add(label4);
			_gridItems.Widgets.Add(label5);
			_gridItems.Widgets.Add(label6);

			var horizontalSeparator1 = new HorizontalSeparator();

			_buttonTakeAll = new TextButton();
			_buttonTakeAll.Text = "/c[green]T/c[white]ake All";
			_buttonTakeAll.Width = 100;
			_buttonTakeAll.Id = "_buttonTakeAll";

			var horizontalStackPanel1 = new HorizontalStackPanel();
			horizontalStackPanel1.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Right;
			horizontalStackPanel1.Widgets.Add(_buttonTakeAll);

			var verticalStackPanel1 = new VerticalStackPanel();
			verticalStackPanel1.Widgets.Add(_gridItems);
			verticalStackPanel1.Widgets.Add(horizontalSeparator1);
			verticalStackPanel1.Widgets.Add(horizontalStackPanel1);

			
			Title = "Take";
			Left = 808;
			Top = 410;
			Width = 300;
			Content = verticalStackPanel1;
		}

		
		public Grid _gridItems;
		public TextButton _buttonTakeAll;
	}
}
