/* Generated by MyraPad at 12/4/2020 8:35:51 PM */
using Jord.Core.Items;
using Myra.Extended.Widgets;
using Myra.Graphics2D.UI;

namespace Jord.UI
{
	public partial class TanningWindow
	{
		public TanningWindow()
		{
			BuildUI();

			_listBoxItems.AcceptsKeyboardFocus = false;

			var arrow = new Arrow
			{
				Direction = ArrowDirection.Right
			};

			_panelArrow.Widgets.Add(arrow);

			_listBoxItems.SelectedIndexChanged += _listBoxItems_SelectedIndexChanged;
			_buttonTan.Click += _buttonTan_Click;

			Rebuild();
		}

		private void _buttonTan_Click(object sender, System.EventArgs e)
		{
			var lastIndex = _listBoxItems.SelectedIndex.Value;

			// Remove item
			var itemPile = (ItemPile)_listBoxItems.SelectedItem.Tag;
			var player = TJ.Player;
			player.Inventory.Add(itemPile.Item, -1);

			// Add tanning result
			foreach(var item in itemPile.Item.Info.TanningResult.Items)
			{
				player.Inventory.Add(item.Item, item.Quantity);
			}

			Rebuild();

			if (lastIndex < _listBoxItems.Items.Count)
			{
				_listBoxItems.SelectedIndex = lastIndex;
			}
		}

		private void _listBoxItems_SelectedIndexChanged(object sender, System.EventArgs e)
		{
			_labelResult.Text = string.Empty;

			if (_listBoxItems.SelectedIndex == null)
			{
				return;
			}

			var itemPile = (ItemPile)_listBoxItems.SelectedItem.Tag;
			_labelResult.Text = itemPile.Item.Info.TanningResult.ToString();
			UpdateButtons();
		}

		private void Rebuild()
		{
			_listBoxItems.Items.Clear();
			_labelResult.Text = string.Empty;

			var inventory = TJ.Player.Inventory;
			foreach(var item in inventory.Items)
			{
				var tanning = item.Item.Info.TanningResult;
				if (tanning != null && tanning.Count > 0)
				{
					_listBoxItems.Items.Add(new ListItem
					{
						Text = item.ToString(),
						Tag = item
					});
				}
			}

			_listBoxComponents.Items.Clear();
			foreach (var item in inventory.Items)
			{
				if (item.Item.Info.Type == ItemType.Component)
				{
					_listBoxComponents.Items.Add(new ListItem
					{
						Text = item.ToString()
					});
				}
			}

			UpdateButtons();
		}

		private void UpdateButtons()
		{
			_buttonTan.Enabled = _listBoxItems.SelectedIndex != null;
		}
	}
}