/* Generated by MyraPad at 12/7/2020 1:12:31 AM */
using Myra;
using Myra.Graphics2D;
using Myra.Graphics2D.TextureAtlases;
using Myra.Graphics2D.UI;
using Myra.Graphics2D.Brushes;

#if !STRIDE
using Microsoft.Xna.Framework;
using Microsoft.Xna.Framework.Graphics;
#else
using Stride.Core.Mathematics;
#endif

namespace Jord.UI
{
	partial class TanningWindow: Window
	{
		private void BuildUI()
		{
			var horizontalSeparator1 = new HorizontalSeparator();

			var listItem1 = new ListItem();
			listItem1.Text = "Rat Skin (5)";

			var listItem2 = new ListItem();
			listItem2.Text = "Leather Armor (2)";

			var listItem3 = new ListItem();
			listItem3.Text = "Wolf Skin";

			_listBoxItems = new ListBox();
			_listBoxItems.Width = 200;
			_listBoxItems.Height = 200;
			_listBoxItems.Id = "_listBoxItems";
			_listBoxItems.Items.Add(listItem1);
			_listBoxItems.Items.Add(listItem2);
			_listBoxItems.Items.Add(listItem3);

			var verticalSeparator1 = new VerticalSeparator();

			_labelResult = new Label();
			_labelResult.Text = "Leather(2)";
			_labelResult.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Center;
			_labelResult.Id = "_labelResult";

			_panelArrow = new Panel();
			_panelArrow.Id = "_panelArrow";

			var verticalStackPanel1 = new VerticalStackPanel();
			verticalStackPanel1.VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Center;
			verticalStackPanel1.Width = 200;
			verticalStackPanel1.Widgets.Add(_labelResult);
			verticalStackPanel1.Widgets.Add(_panelArrow);

			var verticalSeparator2 = new VerticalSeparator();

			var listItem4 = new ListItem();
			listItem4.Text = "Leather(2)";

			_listBoxComponents = new ListBox();
			_listBoxComponents.Enabled = false;
			_listBoxComponents.Width = 200;
			_listBoxComponents.Height = 200;
			_listBoxComponents.Id = "_listBoxComponents";
			_listBoxComponents.Items.Add(listItem4);

			var horizontalStackPanel1 = new HorizontalStackPanel();
			horizontalStackPanel1.Widgets.Add(_listBoxItems);
			horizontalStackPanel1.Widgets.Add(verticalSeparator1);
			horizontalStackPanel1.Widgets.Add(verticalStackPanel1);
			horizontalStackPanel1.Widgets.Add(verticalSeparator2);
			horizontalStackPanel1.Widgets.Add(_listBoxComponents);

			var horizontalSeparator2 = new HorizontalSeparator();

			_buttonTan = new TextButton();
			_buttonTan.Text = "\\c[green]T\\c[white]an";
			_buttonTan.Width = 120;
			_buttonTan.Id = "_buttonTan";

			var horizontalStackPanel2 = new HorizontalStackPanel();
			horizontalStackPanel2.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Right;
			horizontalStackPanel2.Widgets.Add(_buttonTan);

			var verticalStackPanel2 = new VerticalStackPanel();
			verticalStackPanel2.Widgets.Add(horizontalSeparator1);
			verticalStackPanel2.Widgets.Add(horizontalStackPanel1);
			verticalStackPanel2.Widgets.Add(horizontalSeparator2);
			verticalStackPanel2.Widgets.Add(horizontalStackPanel2);

			
			Title = "Leather Tanning Bench";
			Left = 369;
			Top = 141;
			Content = verticalStackPanel2;
		}

		
		public ListBox _listBoxItems;
		public Label _labelResult;
		public Panel _panelArrow;
		public ListBox _listBoxComponents;
		public TextButton _buttonTan;
	}
}
