using System;
using System.Collections.Generic;
using Jord.Core;
using Jord.Utils;

namespace Jord.Generation
{
	public static class MapGeneration
	{
		private const int Levels = 100;

		private class CreatureRandom
		{
			public CreatureInfo Info;
			public float Rate;
			public float Threshold;
		}

		private static void FillCity(Map map)
		{

		}

		private static void FillDungeon(BaseGenerator generator, Map map, int level)
		{
			var freeTiles = new List<Tile>();
			for (var x = 0; x < map.Width; ++x)
			{
				for (var y = 0; y < map.Height; ++y)
				{
					var tile = map[x, y];
					if (tile.Info.Passable && tile.Object == null && tile.Creature == null)
					{
						freeTiles.Add(tile);
					}
				}
			}

			if (freeTiles.Count == 0)
			{
				throw new Exception(string.Format("Could not find free tile at map generated by generator '{0}'", generator.Id));
			}

			// Back exits
			var count = MathUtils.Random.Next(1, 3);
			for (var i = 0; i < count; ++i)
			{
				var index = MathUtils.Random.Next(0, freeTiles.Count);
				var exitTile = freeTiles[index];
				freeTiles.RemoveAt(index);

				exitTile.Info = TJ.Database.ExitUp;
			}

			// Down exits
			if (level <= Levels)
			{
				count = MathUtils.Random.Next(2, 5);
				for (var i = 0; i < count; ++i)
				{
					var index = MathUtils.Random.Next(0, freeTiles.Count);
					var exitTile = freeTiles[index];
					freeTiles.RemoveAt(index);

					exitTile.Info = TJ.Database.ExitDown;
				}
			}

			// Add creatures
			var creaturesAmount = (int)Math.Sqrt(map.Width * map.Height) / 4;

			var possibleCreatures = new List<CreatureRandom>();
			var totalRate = 0.0f;
			foreach (var pair in TJ.Database.CreatureInfos)
			{
				var info = pair.Value;
				if (info.MinimumLevel== 0 || info.MinimumLevel > level)
				{
					continue;
				}

				var creatureRandom = new CreatureRandom
				{
					Info = info,
					Rate = info.Occurence / (float)(level - info.MinimumLevel + 1)
				};

				totalRate += creatureRandom.Rate;

				possibleCreatures.Add(creatureRandom);
			}

			// Normalize rates
			var threshold = 0.0f;
			foreach (var cr in possibleCreatures)
			{
				cr.Rate /= totalRate;

				threshold += cr.Rate;
				cr.Threshold = threshold;
			}

			if (possibleCreatures.Count > 0)
			{
				for (var i = 0; i < creaturesAmount; ++i)
				{
					if (freeTiles.Count == 0)
					{
						break;
					}

					var rnd = (float)MathUtils.Random.NextDouble();

					// Determine creature
					CreatureRandom creatureRandom = possibleCreatures[0];
					foreach (var cr in possibleCreatures)
					{
						if (rnd < cr.Threshold)
						{
							creatureRandom = cr;
							break;
						}
					}

					var npc = new NonPlayer(creatureRandom.Info);

					var index = MathUtils.Random.Next(0, freeTiles.Count);
					var tile = freeTiles[index];
					freeTiles.RemoveAt(index);

					npc.Place(map, tile.Position);
				}
			}
		}

		public static Map Generate(int level)
		{
			// Find the dungeon record
			DungeonRecord dungeonRecord = null;

			foreach (var dr in TJ.Database.DungeonInfo)
			{
				if (dr.MinimumLevel > level)
				{
					break;
				}

				dungeonRecord = dr;
			}

			var generator = dungeonRecord.Generator;

			// Generate the map
			var map = generator.Generate();
			map.Level = level;

			if (level > 0)
			{
				FillDungeon(generator, map, level);
			}

			return map;
		}
	}
}
