/* Generated by MyraPad at 8/20/2020 4:48:54 PM */
using Myra.Graphics2D;
using Myra.Graphics2D.TextureAtlases;
using Myra.Graphics2D.UI;
using Myra.Graphics2D.Brushes;

#if !XENKO
using Microsoft.Xna.Framework;
using Microsoft.Xna.Framework.Graphics;
#else
using Xenko.Core.Mathematics;
#endif

namespace TroublesOfJord.UI
{
	partial class AbilitiesWindow: Window
	{
		private void BuildUI()
		{
			var listItem1 = new ListItem();
			listItem1.Text = "Double Attack";

			var listItem2 = new ListItem();
			listItem2.Text = "Parry";
			listItem2.Color = Color.Red;

			var listItem3 = new ListItem();
			listItem3.Text = "Spell 'Cure Light Wounds'";

			var listItem4 = new ListItem();
			listItem4.Text = "Spell 'Cure Minor Wounds'";

			var listItem5 = new ListItem();
			listItem5.Text = "Spell 'Cure Normal Wounds'";

			var listItem6 = new ListItem();
			listItem6.Text = "Spell 'Cure Serious Wounds'";

			_listAbilities = new ListBox();
			_listAbilities.VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Stretch;
			_listAbilities.Id = "_listAbilities";
			_listAbilities.Items.Add(listItem1);
			_listAbilities.Items.Add(listItem2);
			_listAbilities.Items.Add(listItem3);
			_listAbilities.Items.Add(listItem4);
			_listAbilities.Items.Add(listItem5);
			_listAbilities.Items.Add(listItem6);

			var verticalSeparator1 = new VerticalSeparator();

			_labelEnergyCost = new Label();
			_labelEnergyCost.Text = "0 Energy";
			_labelEnergyCost.Id = "_labelEnergyCost";

			var horizontalSeparator1 = new HorizontalSeparator();

			_labelType = new Label();
			_labelType.Text = "On/Off";
			_labelType.Id = "_labelType";

			var horizontalSeparator2 = new HorizontalSeparator();

			var label1 = new Label();
			label1.Text = "Replaces first attack with parry, which is blocks first attack of enemy with almost 100% guarantee";
			label1.Wrap = true;
			label1.Width = 200;

			var verticalStackPanel1 = new VerticalStackPanel();
			verticalStackPanel1.Spacing = 4;
			verticalStackPanel1.Widgets.Add(_labelEnergyCost);
			verticalStackPanel1.Widgets.Add(horizontalSeparator1);
			verticalStackPanel1.Widgets.Add(_labelType);
			verticalStackPanel1.Widgets.Add(horizontalSeparator2);
			verticalStackPanel1.Widgets.Add(label1);

			var horizontalStackPanel1 = new HorizontalStackPanel();
			horizontalStackPanel1.Widgets.Add(_listAbilities);
			horizontalStackPanel1.Widgets.Add(verticalSeparator1);
			horizontalStackPanel1.Widgets.Add(verticalStackPanel1);

			
			Title = "Abilities";
			Left = 386;
			Top = 121;
			Width = 400;
			Content = horizontalStackPanel1;
		}

		
		public ListBox _listAbilities;
		public Label _labelEnergyCost;
		public Label _labelType;
	}
}