/* Generated by MyraPad at 8/20/2020 4:48:54 PM */
using Myra.Graphics2D.UI;

namespace TroublesOfJord.UI
{
	public partial class AbilitiesWindow
	{
		public AbilitiesWindow()
		{
			BuildUI();
			RebuildAbilities();
		}

		private void RebuildAbilities()
		{
			var player = TJ.Player;

			_listAbilities.Items.Clear();

			foreach(var ability in player.Abilities)
			{
				_listAbilities.Items.Add(new ListItem(ability.Name, null, ability));
			}

		}
	}
}