/* Generated by MyraPad at 07.08.2020 10:50:37 */
using System;
using TroublesOfJord.Core;

namespace TroublesOfJord.UI
{
	public partial class CharacterWindow
	{
		public Player Player { get; }

		public CharacterWindow(Player player)
		{
			BuildUI();

			Player = player ?? throw new ArgumentNullException(nameof(player));

			_labelDescription.Text = string.Format("{0}, {1}, {2}",
				player.Name, player.Class.Name, player.Level);


		}

		private void ResetPoints()
		{

		}
	}
}