/* Generated by MyraPad at 07.08.2020 11:19:30 */
using Myra.Graphics2D;
using Myra.Graphics2D.TextureAtlases;
using Myra.Graphics2D.UI;
using Myra.Graphics2D.Brushes;

#if !XENKO
using Microsoft.Xna.Framework;
using Microsoft.Xna.Framework.Graphics;
#else
using Xenko.Core.Mathematics;
#endif

namespace TroublesOfJord.UI
{
	partial class CharacterWIndow: Window
	{
		private void BuildUI()
		{
			var horizontalSeparator1 = new HorizontalSeparator();

			var label1 = new Label();
			label1.Text = "rds, Warrior, 10";

			var horizontalSeparator2 = new HorizontalSeparator();

			var label2 = new Label();
			label2.Text = "You have 10 points left to distribute.";

			var label3 = new Label();
			label3.Text = "Warrior";

			var spinButton1 = new SpinButton();
			spinButton1.Width = 40;
			spinButton1.GridColumn = 1;

			var label4 = new Label();
			label4.Text = "Thief";
			label4.GridRow = 1;

			var spinButton2 = new SpinButton();
			spinButton2.Width = 40;
			spinButton2.GridColumn = 1;
			spinButton2.GridRow = 1;

			var label5 = new Label();
			label5.Text = "Priest";
			label5.GridRow = 2;

			var spinButton3 = new SpinButton();
			spinButton3.Width = 40;
			spinButton3.GridColumn = 1;
			spinButton3.GridRow = 2;

			var label6 = new Label();
			label6.Text = "Mage";
			label6.GridRow = 3;

			var spinButton4 = new SpinButton();
			spinButton4.Width = 40;
			spinButton4.GridColumn = 1;
			spinButton4.GridRow = 3;

			var grid1 = new Grid();
			grid1.ColumnSpacing = 8;
			grid1.RowSpacing = 8;
			grid1.Widgets.Add(label3);
			grid1.Widgets.Add(spinButton1);
			grid1.Widgets.Add(label4);
			grid1.Widgets.Add(spinButton2);
			grid1.Widgets.Add(label5);
			grid1.Widgets.Add(spinButton3);
			grid1.Widgets.Add(label6);
			grid1.Widgets.Add(spinButton4);

			var textButton1 = new TextButton();
			textButton1.Text = "Confirm";

			var textButton2 = new TextButton();
			textButton2.Text = "Reset";

			var horizontalStackPanel1 = new HorizontalStackPanel();
			horizontalStackPanel1.Spacing = 8;
			horizontalStackPanel1.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Left;
			horizontalStackPanel1.Widgets.Add(textButton1);
			horizontalStackPanel1.Widgets.Add(textButton2);

			var horizontalSeparator3 = new HorizontalSeparator();

			var label7 = new Label();
			label7.Text = "HP: 50/100";

			var label8 = new Label();
			label8.Text = "EN: 50/100";
			label8.GridColumn = 1;

			var label9 = new Label();
			label9.Text = "HP Regen: 10";
			label9.GridRow = 1;

			var label10 = new Label();
			label10.Text = "EN Regen: 5";
			label10.GridColumn = 1;
			label10.GridRow = 1;

			var label11 = new Label();
			label11.Text = "AC: 120";
			label11.GridRow = 2;

			var label12 = new Label();
			label12.Text = "Hit: 10";
			label12.GridColumn = 1;
			label12.GridRow = 2;

			var label13 = new Label();
			label13.Text = "Attacks: 3";
			label13.GridRow = 3;

			var label14 = new Label();
			label14.Text = "Dam: 10";
			label14.GridColumn = 1;
			label14.GridRow = 3;

			var grid2 = new Grid();
			grid2.ColumnSpacing = 8;
			grid2.RowSpacing = 8;
			grid2.Widgets.Add(label7);
			grid2.Widgets.Add(label8);
			grid2.Widgets.Add(label9);
			grid2.Widgets.Add(label10);
			grid2.Widgets.Add(label11);
			grid2.Widgets.Add(label12);
			grid2.Widgets.Add(label13);
			grid2.Widgets.Add(label14);

			var verticalStackPanel1 = new VerticalStackPanel();
			verticalStackPanel1.Spacing = 8;
			verticalStackPanel1.Widgets.Add(horizontalSeparator1);
			verticalStackPanel1.Widgets.Add(label1);
			verticalStackPanel1.Widgets.Add(horizontalSeparator2);
			verticalStackPanel1.Widgets.Add(label2);
			verticalStackPanel1.Widgets.Add(grid1);
			verticalStackPanel1.Widgets.Add(horizontalStackPanel1);
			verticalStackPanel1.Widgets.Add(horizontalSeparator3);
			verticalStackPanel1.Widgets.Add(grid2);

			
			Title = "Character";
			IsDraggable = false;
			Left = 436;
			Top = 16;
			Width = 300;
			Content = verticalStackPanel1;
		}

		
	}
}