/* Generated by MyraPad at 8/11/2020 12:15:41 PM */
using Myra.Graphics2D;
using Myra.Graphics2D.TextureAtlases;
using Myra.Graphics2D.UI;
using Myra.Graphics2D.Brushes;

#if !XENKO
using Microsoft.Xna.Framework;
using Microsoft.Xna.Framework.Graphics;
#else
using Xenko.Core.Mathematics;
#endif

namespace TroublesOfJord.UI
{
	partial class CharacterWindow: Window
	{
		private void BuildUI()
		{
			var horizontalSeparator1 = new HorizontalSeparator();

			_labelDescription = new Label();
			_labelDescription.Text = "rds, Warrior, 10";
			_labelDescription.Id = "_labelDescription";

			var horizontalSeparator2 = new HorizontalSeparator();

			_labelPointsLeft = new Label();
			_labelPointsLeft.Text = "You have 10 points left to distribute.";
			_labelPointsLeft.Id = "_labelPointsLeft";

			var label1 = new Label();
			label1.Text = "Warrior";

			var spinButton1 = new SpinButton();
			spinButton1.Width = 40;
			spinButton1.GridColumn = 1;

			var label2 = new Label();
			label2.Text = "Thief";
			label2.GridRow = 1;

			var spinButton2 = new SpinButton();
			spinButton2.Width = 40;
			spinButton2.GridColumn = 1;
			spinButton2.GridRow = 1;

			var label3 = new Label();
			label3.Text = "Priest";
			label3.GridRow = 2;

			var spinButton3 = new SpinButton();
			spinButton3.Width = 40;
			spinButton3.GridColumn = 1;
			spinButton3.GridRow = 2;

			var label4 = new Label();
			label4.Text = "Mage";
			label4.GridRow = 3;

			var spinButton4 = new SpinButton();
			spinButton4.Width = 40;
			spinButton4.GridColumn = 1;
			spinButton4.GridRow = 3;

			_gridClasses = new Grid();
			_gridClasses.ColumnSpacing = 8;
			_gridClasses.RowSpacing = 8;
			_gridClasses.Id = "_gridClasses";
			_gridClasses.Widgets.Add(label1);
			_gridClasses.Widgets.Add(spinButton1);
			_gridClasses.Widgets.Add(label2);
			_gridClasses.Widgets.Add(spinButton2);
			_gridClasses.Widgets.Add(label3);
			_gridClasses.Widgets.Add(spinButton3);
			_gridClasses.Widgets.Add(label4);
			_gridClasses.Widgets.Add(spinButton4);

			_buttonConfirm = new TextButton();
			_buttonConfirm.Text = "Confirm";
			_buttonConfirm.Id = "_buttonConfirm";

			_buttonReset = new TextButton();
			_buttonReset.Text = "Reset";
			_buttonReset.Id = "_buttonReset";

			var horizontalStackPanel1 = new HorizontalStackPanel();
			horizontalStackPanel1.Spacing = 8;
			horizontalStackPanel1.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Left;
			horizontalStackPanel1.Widgets.Add(_buttonConfirm);
			horizontalStackPanel1.Widgets.Add(_buttonReset);

			var horizontalSeparator3 = new HorizontalSeparator();

			_labelHp = new Label();
			_labelHp.Text = "HP: 50/100(+10)";
			_labelHp.Id = "_labelHp";

			_labelEnergy = new Label();
			_labelEnergy.Text = "EN: 50/100(+5)";
			_labelEnergy.GridColumn = 1;
			_labelEnergy.Id = "_labelEnergy";

			_labelAc = new Label();
			_labelAc.Text = "AC: 120";
			_labelAc.GridRow = 1;
			_labelAc.Id = "_labelAc";

			_labelHit = new Label();
			_labelHit.Text = "Hit: 10";
			_labelHit.GridColumn = 1;
			_labelHit.GridRow = 1;
			_labelHit.Id = "_labelHit";

			var label5 = new Label();
			label5.Text = "Attacks: 3";
			label5.GridRow = 2;

			var label6 = new Label();
			label6.Text = "Dam: 10";
			label6.GridColumn = 1;
			label6.GridRow = 2;

			var grid1 = new Grid();
			grid1.ColumnSpacing = 8;
			grid1.RowSpacing = 8;
			grid1.Widgets.Add(_labelHp);
			grid1.Widgets.Add(_labelEnergy);
			grid1.Widgets.Add(_labelAc);
			grid1.Widgets.Add(_labelHit);
			grid1.Widgets.Add(label5);
			grid1.Widgets.Add(label6);

			var verticalStackPanel1 = new VerticalStackPanel();
			verticalStackPanel1.Spacing = 8;
			verticalStackPanel1.Widgets.Add(horizontalSeparator1);
			verticalStackPanel1.Widgets.Add(_labelDescription);
			verticalStackPanel1.Widgets.Add(horizontalSeparator2);
			verticalStackPanel1.Widgets.Add(_labelPointsLeft);
			verticalStackPanel1.Widgets.Add(_gridClasses);
			verticalStackPanel1.Widgets.Add(horizontalStackPanel1);
			verticalStackPanel1.Widgets.Add(horizontalSeparator3);
			verticalStackPanel1.Widgets.Add(grid1);

			
			Title = "Character";
			IsDraggable = false;
			Left = 436;
			Top = 31;
			Width = 300;
			Content = verticalStackPanel1;
		}

		
		public Label _labelDescription;
		public Label _labelPointsLeft;
		public Grid _gridClasses;
		public TextButton _buttonConfirm;
		public TextButton _buttonReset;
		public Label _labelHp;
		public Label _labelEnergy;
		public Label _labelAc;
		public Label _labelHit;
	}
}