/* Generated by MyraPad at 10/19/2020 12:44:13 PM */
using Myra.Graphics2D;
using Myra.Graphics2D.TextureAtlases;
using Myra.Graphics2D.UI;
using Myra.Graphics2D.Brushes;

#if !STRIDE
using Microsoft.Xna.Framework;
using Microsoft.Xna.Framework.Graphics;
#else
using Stride.Core.Mathematics;
#endif

namespace TroublesOfJord.UI
{
	partial class GameView: HorizontalStackPanel
	{
		private void BuildUI()
		{
			_mapViewContainer = new Panel();
			_mapViewContainer.Id = "_mapViewContainer";

			var verticalSeparator1 = new VerticalSeparator();

			_labelHp = new Label();
			_labelHp.Text = "HP: 50/100";
			_labelHp.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Center;
			_labelHp.Id = "_labelHp";

			var verticalSeparator2 = new VerticalSeparator();

			_labelEnergy = new Label();
			_labelEnergy.Text = "EN: 50/100";
			_labelEnergy.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Center;
			_labelEnergy.Id = "_labelEnergy";

			var horizontalStackPanel1 = new HorizontalStackPanel();
			horizontalStackPanel1.Proportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Part,
			});
			horizontalStackPanel1.Proportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Auto,
			});
			horizontalStackPanel1.Proportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Part,
			});
			horizontalStackPanel1.Widgets.Add(_labelHp);
			horizontalStackPanel1.Widgets.Add(verticalSeparator2);
			horizontalStackPanel1.Widgets.Add(_labelEnergy);

			var horizontalSeparator1 = new HorizontalSeparator();

			_mapContainer = new Panel();
			_mapContainer.Height = 247;
			_mapContainer.Id = "_mapContainer";

			var horizontalSeparator2 = new HorizontalSeparator();

			_logContainer = new Panel();
			_logContainer.Id = "_logContainer";

			var verticalStackPanel1 = new VerticalStackPanel();
			verticalStackPanel1.Proportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Auto,
			});
			verticalStackPanel1.Proportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Auto,
			});
			verticalStackPanel1.Proportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Auto,
			});
			verticalStackPanel1.Proportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Auto,
			});
			verticalStackPanel1.Proportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Fill,
			});
			verticalStackPanel1.Widgets.Add(horizontalStackPanel1);
			verticalStackPanel1.Widgets.Add(horizontalSeparator1);
			verticalStackPanel1.Widgets.Add(_mapContainer);
			verticalStackPanel1.Widgets.Add(horizontalSeparator2);
			verticalStackPanel1.Widgets.Add(_logContainer);

			
			Proportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Part,
				Value = 2,
			});
			Proportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Auto,
			});
			Proportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Part,
			});
			Widgets.Add(_mapViewContainer);
			Widgets.Add(verticalSeparator1);
			Widgets.Add(verticalStackPanel1);
		}

		
		public Panel _mapViewContainer;
		public Label _labelHp;
		public Label _labelEnergy;
		public Panel _mapContainer;
		public Panel _logContainer;
	}
}