/* Generated by MyraPad at 08.11.2019 0:52:31 */
using Myra.Graphics2D.UI;

#if !XENKO
using Microsoft.Xna.Framework;
#else
using Xenko.Core.Mathematics;
#endif

namespace TroublesOfJord.UI
{
	partial class SkillWidget: Grid
	{
		private void BuildUI()
		{
			_labelIndex = new Label();
			_labelIndex.Text = "5";
			_labelIndex.Id = "_labelIndex";

			_checkBoxAuto = new CheckBox();
			_checkBoxAuto.Text = "";
			_checkBoxAuto.Id = "_checkBoxAuto";
			_checkBoxAuto.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Center;
			_checkBoxAuto.GridColumn = 1;

			_buttonSkill = new TextButton();
			_buttonSkill.Text = "Kick";
			_buttonSkill.Id = "_buttonSkill";
			_buttonSkill.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Stretch;
			_buttonSkill.VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Stretch;
			_buttonSkill.GridRow = 1;
			_buttonSkill.GridColumnSpan = 2;

			
			ColumnSpacing = 4;
			RowSpacing = 4;
			ColumnsProportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Auto,
			});
			ColumnsProportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Fill,
			});
			RowsProportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Auto,
			});
			RowsProportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Fill,
			});
			Widgets.Add(_labelIndex);
			Widgets.Add(_checkBoxAuto);
			Widgets.Add(_buttonSkill);
		}

		
		public Label _labelIndex;
		public CheckBox _checkBoxAuto;
		public TextButton _buttonSkill;
	}
}