/* Generated by MyraPad at 30.10.2019 2:24:34 */
using Myra.Graphics2D.UI;

#if !XENKO
using Microsoft.Xna.Framework;
#else
using Xenko.Core.Mathematics;
#endif

namespace TroublesOfJord.UI
{
	partial class TradeDialog: Dialog
	{
		private void BuildUI()
		{
			_textNameLeft = new Label();
			_textNameLeft.Text = "player";
			_textNameLeft.Id = "_textNameLeft";

			_textGoldLeft = new Label();
			_textGoldLeft.Text = "Gold: 1000";
			_textGoldLeft.Id = "_textGoldLeft";
			_textGoldLeft.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Right;

			var panel1 = new Panel();
			panel1.Widgets.Add(_textNameLeft);
			panel1.Widgets.Add(_textGoldLeft);

			var horizontalSeparator1 = new HorizontalSeparator();

			var label1 = new Label();
			label1.Text = "iron rations(5)";
			label1.GridColumn = 1;

			var label2 = new Label();
			label2.Text = "5";
			label2.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Right;
			label2.GridColumn = 2;

			var label3 = new Label();
			label3.Text = "canteen";
			label3.GridColumn = 1;
			label3.GridRow = 1;

			var label4 = new Label();
			label4.Text = "7";
			label4.GridColumn = 2;
			label4.GridRow = 1;

			_gridLeft = new Grid();
			_gridLeft.ColumnSpacing = 8;
			_gridLeft.RowSpacing = 4;
			_gridLeft.DefaultRowProportion = new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Auto,
			};
			_gridLeft.ColumnsProportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Pixels,
				Value = 16,
			});
			_gridLeft.ColumnsProportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Fill,
			});
			_gridLeft.ColumnsProportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Auto,
			});
			_gridLeft.GridSelectionMode = Myra.Graphics2D.UI.GridSelectionMode.Row;
			_gridLeft.Id = "_gridLeft";
			_gridLeft.Widgets.Add(label1);
			_gridLeft.Widgets.Add(label2);
			_gridLeft.Widgets.Add(label3);
			_gridLeft.Widgets.Add(label4);

			var scrollViewer1 = new ScrollViewer();
			scrollViewer1.Content = _gridLeft;

			var verticalStackPanel1 = new VerticalStackPanel();
			verticalStackPanel1.Widgets.Add(panel1);
			verticalStackPanel1.Widgets.Add(horizontalSeparator1);
			verticalStackPanel1.Widgets.Add(scrollViewer1);

			_textGoldTransfer = new Label();
			_textGoldTransfer.Text = "500";
			_textGoldTransfer.Id = "_textGoldTransfer";
			_textGoldTransfer.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Center;

			_panelArrow = new Panel();
			_panelArrow.Id = "_panelArrow";
			_panelArrow.Height = 20;

			_gridGoldTransfer = new VerticalStackPanel();
			_gridGoldTransfer.VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Center;
			_gridGoldTransfer.Id = "_gridGoldTransfer";
			_gridGoldTransfer.Widgets.Add(_textGoldTransfer);
			_gridGoldTransfer.Widgets.Add(_panelArrow);

			_textNameRight = new Label();
			_textNameRight.Text = "merchant";
			_textNameRight.Id = "_textNameRight";

			_textGoldRight = new Label();
			_textGoldRight.Text = "Gold: 50000";
			_textGoldRight.Id = "_textGoldRight";
			_textGoldRight.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Right;

			var panel2 = new Panel();
			panel2.Widgets.Add(_textNameRight);
			panel2.Widgets.Add(_textGoldRight);

			var horizontalSeparator2 = new HorizontalSeparator();

			var label5 = new Label();
			label5.Text = "iron rations(100)";
			label5.GridColumn = 1;

			var label6 = new Label();
			label6.Text = "10";
			label6.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Right;
			label6.GridColumn = 2;

			var label7 = new Label();
			label7.Text = "canteen";
			label7.GridColumn = 1;
			label7.GridRow = 1;

			var label8 = new Label();
			label8.Text = "15";
			label8.GridColumn = 2;
			label8.GridRow = 1;

			var label9 = new Label();
			label9.Text = "barrel";
			label9.GridColumn = 1;
			label9.GridRow = 2;

			var label10 = new Label();
			label10.Text = "25";
			label10.GridColumn = 2;
			label10.GridRow = 2;

			var label11 = new Label();
			label11.Text = "short sword";
			label11.GridColumn = 1;
			label11.GridRow = 3;

			var label12 = new Label();
			label12.Text = "50";
			label12.GridColumn = 2;
			label12.GridRow = 3;

			var label13 = new Label();
			label13.Text = "leather armor";
			label13.GridColumn = 1;
			label13.GridRow = 4;

			var label14 = new Label();
			label14.Text = "40";
			label14.GridColumn = 2;
			label14.GridRow = 4;

			var label15 = new Label();
			label15.Text = "leather leggings";
			label15.GridColumn = 1;
			label15.GridRow = 5;

			var label16 = new Label();
			label16.Text = "30";
			label16.GridColumn = 2;
			label16.GridRow = 5;

			var label17 = new Label();
			label17.Text = "small shield";
			label17.GridColumn = 1;
			label17.GridRow = 6;

			var label18 = new Label();
			label18.Text = "25";
			label18.GridColumn = 2;
			label18.GridRow = 6;

			_gridRight = new Grid();
			_gridRight.ColumnSpacing = 8;
			_gridRight.RowSpacing = 4;
			_gridRight.DefaultRowProportion = new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Auto,
			};
			_gridRight.ColumnsProportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Pixels,
				Value = 16,
			});
			_gridRight.ColumnsProportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Fill,
			});
			_gridRight.ColumnsProportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Auto,
			});
			_gridRight.GridSelectionMode = Myra.Graphics2D.UI.GridSelectionMode.Row;
			_gridRight.Id = "_gridRight";
			_gridRight.Widgets.Add(label5);
			_gridRight.Widgets.Add(label6);
			_gridRight.Widgets.Add(label7);
			_gridRight.Widgets.Add(label8);
			_gridRight.Widgets.Add(label9);
			_gridRight.Widgets.Add(label10);
			_gridRight.Widgets.Add(label11);
			_gridRight.Widgets.Add(label12);
			_gridRight.Widgets.Add(label13);
			_gridRight.Widgets.Add(label14);
			_gridRight.Widgets.Add(label15);
			_gridRight.Widgets.Add(label16);
			_gridRight.Widgets.Add(label17);
			_gridRight.Widgets.Add(label18);

			var scrollViewer2 = new ScrollViewer();
			scrollViewer2.Content = _gridRight;

			var verticalStackPanel2 = new VerticalStackPanel();
			verticalStackPanel2.Widgets.Add(panel2);
			verticalStackPanel2.Widgets.Add(horizontalSeparator2);
			verticalStackPanel2.Widgets.Add(scrollViewer2);

			var horizontalStackPanel1 = new HorizontalStackPanel();
			horizontalStackPanel1.Spacing = 8;
			horizontalStackPanel1.Proportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Part,
			});
			horizontalStackPanel1.Proportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Pixels,
				Value = 100,
			});
			horizontalStackPanel1.Proportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Part,
			});
			horizontalStackPanel1.Widgets.Add(verticalStackPanel1);
			horizontalStackPanel1.Widgets.Add(_gridGoldTransfer);
			horizontalStackPanel1.Widgets.Add(verticalStackPanel2);

			var horizontalSeparator3 = new HorizontalSeparator();

			_textDescription = new Label();
			_textDescription.Text = "short sword - weapon, damage: 3-8";
			_textDescription.Id = "_textDescription";

			var verticalStackPanel3 = new VerticalStackPanel();
			verticalStackPanel3.Proportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Fill,
			});
			verticalStackPanel3.Width = 800;
			verticalStackPanel3.Height = 400;
			verticalStackPanel3.PaddingTop = 16;
			verticalStackPanel3.PaddingBottom = 16;
			verticalStackPanel3.Widgets.Add(horizontalStackPanel1);
			verticalStackPanel3.Widgets.Add(horizontalSeparator3);
			verticalStackPanel3.Widgets.Add(_textDescription);

			
			Title = "Trade";
			Left = 124;
			Content = verticalStackPanel3;
		}

		
		public Label _textNameLeft;
		public Label _textGoldLeft;
		public Grid _gridLeft;
		public Label _textGoldTransfer;
		public Panel _panelArrow;
		public VerticalStackPanel _gridGoldTransfer;
		public Label _textNameRight;
		public Label _textGoldRight;
		public Grid _gridRight;
		public Label _textDescription;
	}
}